---
services:

  chromadb:
    image: chromadb/chroma:latest
    hostname: chromadb
    container_name: chromadb
    ports:
      - "8000:8000"

  # https://ngrok.com/docs/using-ngrok-with/docker/
  ngrok:
    image: ngrok/ngrok:latest
    hostname: ngrok
    container_name: ngrok
    ports:
      - 4040:4040
    restart: unless-stopped
    depends_on:
      - chromadb
    command:
      - "start"
      - "--all"
      - "--log=stdout"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ../../ccloud/fm-chromadb-sink/ngrok.yml:/etc/ngrok.yml
    environment:
      NGROK_AUTHTOKEN: $NGROK_AUTH_TOKEN
