---
services:
  mongodb:
    # https://jira.mongodb.org/browse/SERVER-72839
    image: mongo:7.0.5
    hostname: mongodb
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ../../connect/connect-debezium-mongodb-source/ssl/mongo.pem:/tmp/mongo.pem
    environment:
      MONGO_INITDB_ROOT_USERNAME: debezium
      MONGO_INITDB_ROOT_PASSWORD: dbz
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "debezium","--tlsMode", "requireTLS","--tlsCertificateKeyFile", "/tmp/mongo.pem", "--tlsCertificateKeyFilePassword", "confluent"]


  connect:
    depends_on:
      - mongodb
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/debezium-debezium-connector-mongodb
    volumes:
        - ../../connect/connect-debezium-mongodb-source/ssl/truststore.jks:/tmp/truststore.jks
