{
 "title": "Consumers",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "client_id", "query": "label_values(client_id)" }
  ]
 },
 "panels": [
  {
   "title": "Bytes consumed rate",
   "type": "graph",
   "description": "The average number of bytes consumed per second\n",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_consumer_consumer_fetch_manager_metrics_bytes_consumed_total{topic=\"\", client_id=~\"$client_id\"}[2m])",
     "legendFormat": "{{client_id}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Bytes consumed rate per topic",
   "type": "graph",
   "description": "The average number of bytes consumed per topic per second.\n",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_consumer_consumer_fetch_manager_metrics_bytes_consumed_total{topic!=\"\", client_id=~\"$client_id\"}[2m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Rate of records consumed",
   "type": "graph",
   "description": "The average number of records consumed per second.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_consumer_consumer_fetch_manager_metrics_records_consumed_total{topic=\"\", client_id=~\"$client_id\"}[2m])",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Rate of records consumed per topic",
   "type": "graph",
   "description": "The average number of records consumed per second per topic.\n",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (topic, instance) (rate(kafka_consumer_consumer_fetch_manager_metrics_records_consumed_total{topic!=\"\", client_id=~\"$client_id\"}[2m]))",
     "legendFormat": "{{instance}}-{{topic}}"
    }
   ]
  },
  {
   "title": "Average lag per client and partition",
   "type": "graph",
   "description": "The average lag in terms of number of records for any partition.\n",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_consumer_fetch_manager_metrics_records_lag_avg{client_id=~\"$client_id\"}",
     "legendFormat": "{{instance}}-{{topic}}-{{partition}}"
    }
   ]
  },
  {
   "title": "Avg fetch size",
   "type": "graph",
   "description": "The average number of bytes fetched per request\n",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_consumer_fetch_manager_metrics_fetch_size_avg{client_id=~\"$client_id\"}",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Fetch request latency",
   "type": "graph",
   "description": "The average time taken for a fetch request.\n",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_consumer_fetch_manager_metrics_fetch_latency_avg{client_id=~\"$client_id\"}",
     "legendFormat": "{{client_id}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Fetch request rate",
   "type": "graph",
   "description": "The number of fetch requests per second.\n",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_consumer_consumer_fetch_manager_metrics_fetch_total{client_id=~\"$client_id\"}[2m])",
     "legendFormat": "{{client_id}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Current connection count",
   "type": "graph",
   "description": "Number of simultaneous connections\n",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_consumer_metrics_connection_count{client_id=~\"$client_id\"}",
     "legendFormat": "{{client_id}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Average and max fetch throttle time",
   "type": "graph",
   "description": "The average and thee max throttle times in ms",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_consumer_fetch_manager_metrics_fetch_throttle_time_avg{}",
     "legendFormat": "{{client_id}} - {{instance}}-avg"
    },
    {
     "expr": "kafka_consumer_consumer_fetch_manager_metrics_fetch_throttle_time_max{}",
     "legendFormat": "{{client_id}} - {{instance}}-max"
    }
   ]
  },
  {
   "title": "Record lead",
   "type": "graph",
   "description": "Lag between the earliest offset in partition and the consumer offset\n",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_consumer_fetch_manager_metrics_records_lead{client_id=~\"$client_id\"}",
     "legendFormat": "{{client_id}}-{{instance}}-{{topic}}"
    }
   ]
  },
  {
   "title": "Node reponse rate",
   "type": "graph",
   "description": "response rate per node\n",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_consumer_node_metrics_response_rate{client_id=~\"$client_id\"}"
    }
   ]
  },
  {
   "title": "failed auth rate",
   "type": "graph",
   "description": "Rate of failed authentication attempts\n",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_consumer_metrics_failed_authentication_rate{client_id=~\"$client_id\"}",
     "legendFormat": "{{client_id}}-{{instance}}"
    }
   ]
  }
 ]
}