{
 "title": "Cluster Linking",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(cluster)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(kafka_server_kafkaserver_brokerstate{cluster=\"${cluster}\"}, instance)"
    }
   },
   { "name": "job", "label": "Job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  { "title": "HealthCheck", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Mirror Topics",
   "type": "stat",
   "description": "Total number of active (healthy) mirror topics.\nThis metric is only reported by the controller",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_cluster_link_metrics_mirror_mirror_topic_count{cluster=\"$cluster\", instance=~\"$instance\", job=\"$job\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Failed Mirror Topics",
   "type": "stat",
   "description": "Total number of mirror topics for which mirroring from the source has been paused.\nThis metric is only reported by the controller",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_cluster_link_metrics_failedmirror_mirror_topic_count{cluster=\"$cluster\", instance=~\"$instance\", job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Paused Mirror Topics",
   "type": "stat",
   "description": "Total number of mirror topics for which mirroring from the source has been paused.\nThis metric is only reported by the controller",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_cluster_link_metrics_pausedmirror_mirror_topic_count{cluster=\"$cluster\", instance=~\"$instance\", job=\"$job\"})"
    }
   ]
  },
  {
   "title": "PendingStopped Mirror Topics",
   "type": "stat",
   "description": "Total number of mirrored topics being stopped .\nThis metric is only reported by the controller",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_cluster_link_metrics_pendingstoppedmirror_mirror_topic_count{cluster=\"$cluster\", instance=~\"$instance\", job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Online Mirror Partitions",
   "type": "stat",
   "description": "Total number of active mirrored partitions on all brokers.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_cluster_link_metrics_mirror_partition_count{cluster=\"$cluster\", instance=~\"$instance\", job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Blocked Mirror Partitions",
   "type": "stat",
   "description": "Number of mirrored partitions that are blocked on fetching data due to issues on the source cluster.\n",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_blockedonmirrorsourcepartitioncount{cluster=\"$cluster\", instance=~\"$instance\", job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Under Min ISR Mirror Partitions",
   "type": "stat",
   "description": "Number of mirrored partitions that are under min ISR.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_underminisrmirrorpartitioncount{cluster=\"$cluster\", instance=~\"$instance\", job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Under Replicated Mirror Partitions",
   "type": "stat",
   "description": "Number of mirrored partitions that are under replicated.\n",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_underreplicatedmirrorpartitions{cluster=\"$cluster\", instance=~\"$instance\", job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Cluster Link Consumer Offset Committed Rate",
   "type": "stat",
   "description": "Rate per second of consumer offsets committed for a cluster link.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_cluster_link_metrics_consumer_offset_committed_rate{cluster=\"$cluster\", instance=~\"$instance\", job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Linked Partition Addition Rate",
   "type": "stat",
   "description": "Rate per second of times at which the partition count was updated due to source changes.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_cluster_link_metrics_linked_topic_partition_addition_rate{cluster=\"$cluster\", instance=~\"$instance\", job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Cluster Link Consumer Offset Failed Committed Rate",
   "type": "stat",
   "description": "Rate per second of failed consumer offsets commits for a cluster link.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_cluster_link_metrics_consumer_offset_commit_failed_rate{cluster=\"$cluster\", instance=~\"$instance\", job=\"$job\"})"
    }
   ]
  },
  { "title": "Replication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Link Messages Lag",
   "type": "timeseries",
   "description": "Maximum lag in messages between the replicas on the destination cluster and the leader replica on the source cluster. Provides an indication of overall cluster link health and a relative measure of whether the destination cluster is lagging behind.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_server_link_clusterlinkfetchermanager_maxlag{cluster=\"$cluster\", instance=~\"$instance\", job=\"$job\"}) by (linkName, cluster)",
     "legendFormat": "{{cluster}} - {{linkName}}"
    }
   ]
  },
  {
   "title": "Link Messages Lag Per Topic",
   "type": "timeseries",
   "description": "Drill-down of MaxLag, which provides lag in number of messages per replica on the destination cluster from the leader replica on the source cluster. Useful to debug any specific lagging topic partitions/replicas on the destination cluster.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum({__name__=~\"kafka_server_fetcherlagmetrics_consumerlag_clientid_clusterlinkfetcherthread_[0-9]+_.*\", cluster=\"$cluster\", instance=~\"$instance\", job=\"$job\"}) by (linkName, topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Link Messages Lag Per Broker",
   "type": "timeseries",
   "description": "Maximum lag in messages between the replicas on the destination cluster and the leader replica on the source cluster. Provides an indication of overall cluster link health and a relative measure of whether the destination cluster is lagging behind.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_server_link_clusterlinkfetchermanager_maxlag{cluster=\"$cluster\", instance=~\"$instance\", job=\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Link Fetcher Dead Thread Count",
   "type": "timeseries",
   "description": "Number of dead threads of type ClusterLinkThread, where a dead thread is indicative of an issue with fetching from the source cluster for a partition.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "sum(kafka_server_link_clusterlinkfetchermanager_deadthreadcount{cluster=\"$cluster\", instance=~\"$instance\", job=\"$job\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Link Requests Per Sec",
   "type": "timeseries",
   "description": "Rate at which requests are issued to the source cluster over the cluster link.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(label_replace({__name__=~\"kafka_server_fetcherstats_requestspersec_clientid_clusterlinkfetcherthread_.+\", cluster=\"$cluster\", instance=~\"$instance\", job=\"$job\"}, \"metric_name\", \"$1\", \"__name__\", \"(.+)\")[5m:])) by (cluster, linkName)",
     "legendFormat": "{{cluster}} - {{linkName}}"
    }
   ]
  },
  {
   "title": "Link Bytes Per Sec",
   "type": "timeseries",
   "description": "Rate at which data is fetched from the source cluster. Indicates amount of throughput in bytes per second on the cluster link.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(label_replace({__name__=~\"kafka_server_fetcherstats_bytespersec_clientid_clusterlinkfetcherthread_.*\", cluster=\"$cluster\", instance=~\"$instance\", job=\"$job\"}, \"metric_name\",  \"$1\", \"__name__\", \"(.+)\")[5m:])) by (cluster, linkName)",
     "legendFormat": "{{cluster}} - {{linkName}}"
    }
   ]
  },
  {
   "title": "Link Fetch Throttle Time Average",
   "type": "timeseries",
   "description": "Throttle time metrics may indicate that a cluster link connection is being throttled, which is useful for understanding why lag may be increasing over a cluster link.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "sum(kafka_server_cluster_link_fetch_throttle_time_avg{cluster=\"$cluster\", instance=~\"$instance\", job=\"$job\"}) by (linkName, cluster)"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Link Connection Count",
   "type": "timeseries",
   "description": "Number of connections for a cluster link per destination broker",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "sum(kafka_server_cluster_link_fetcher_metrics_connection_count{cluster=\"$cluster\", instance=~\"$instance\", job=\"$job\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Connection Creation Rate",
   "type": "timeseries",
   "description": "Rate per second for connections created for the cluster link. If the rate is high, the source cluster may be overloaded with connections.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "sum(kafka_server_cluster_link_fetcher_metrics_connection_creation_rate{cluster=\"$cluster\", instance=~\"$instance\", job=\"$job\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Link Bytes In",
   "type": "timeseries",
   "description": "Number of bytes per second received from the source cluster.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(kafka_server_cluster_link_fetcher_metrics_incoming_byte_rate{cluster=\"$cluster\", instance=~\"$instance\", job=\"$job\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Link Connection Close Rate",
   "type": "timeseries",
   "description": "Rate per second for connections closed for the cluster link. Can be compared to connection creation to understand the balance of creating/closing connections.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "targets": [
    {
     "expr": "sum(kafka_server_cluster_link_fetcher_metrics_connection_close_rate{cluster=\"$cluster\", instance=~\"$instance\", job=\"$job\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Link Bytes Out",
   "type": "timeseries",
   "description": "Number of bytes per second sent to the source cluster.\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(kafka_server_cluster_link_fetcher_metrics_outgoing_byte_rate{cluster=\"$cluster\", instance=~\"$instance\", job=\"$job\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "description": "Rate per second of requests issued to the source cluster over the cluster link.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "targets": [
    {
     "expr": "sum(kafka_server_cluster_link_fetcher_metrics_request_rate{cluster=\"$cluster\", instance=~\"$instance\", job=\"$job\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "description": "Number of bytes per second sent to the source cluster.\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "targets": [
    {
     "expr": "sum(kafka_server_cluster_link_fetcher_metrics_network_io_rate{cluster=\"$cluster\", instance=~\"$instance\", job=\"$job\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Response Rate",
   "type": "timeseries",
   "description": "Rate per second of responses received from the source cluster over the cluster link.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "targets": [
    {
     "expr": "sum(kafka_server_cluster_link_fetcher_metrics_response_rate{cluster=\"$cluster\", instance=~\"$instance\", job=\"$job\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request Size Max",
   "type": "timeseries",
   "description": "Max size in bytes of requests issued to the source cluster over the cluster link.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(kafka_server_cluster_link_fetcher_metrics_request_size_max{cluster=\"$cluster\", instance=~\"$instance\", job=\"$job\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request Size Average",
   "type": "timeseries",
   "description": "Average size in bytes of requests issued to the source cluster over the cluster link.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(kafka_server_cluster_link_fetcher_metrics_request_size_avg{cluster=\"$cluster\", instance=~\"$instance\", job=\"$job\"}) by (instance)",
     "legendFormat": "{{intance}}"
    }
   ]
  },
  {
   "title": "I/O Wait Time Average",
   "type": "timeseries",
   "description": "Statistics of the destination cluster’s network IO for the requests over the cluster link.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg(kafka_server_cluster_link_fetcher_metrics_io_wait_time_ns_avg{cluster=\"$cluster\", instance=~\"$instance\", job=\"$job\"}) by (instance)",
     "legendFormat": "{{intance}}"
    }
   ]
  }
 ]
}