{
 "title": "Cluster Linking Overview",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "env", "label": "Environment", "query": { "query": "label_values(env)" } },
   { "name": "link_name", "label": "Link Name", "query": { "query": "label_values(linkName)" } },
   { "name": "broker_id", "label": "Broker Id", "query": { "query": "label_values(brokerId)" } },
   { "name": "fetcher_id", "query": { "query": "label_values(fetcherId)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(kafka_server_kafkaserver_brokerstate, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster link API performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Time Ms (p99)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_totaltimems{job=\"kafka\",env=\"$env\", request=~\"(CreateClusterLinks|DeleteClusterLinks|ListClusterLinks)\", quantile=\"0.99\"}",
     "legendFormat": "{{instance}}-{{request}}"
    }
   ]
  },
  {
   "title": "Local Time Ms (p99)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_localtimems{job=\"kafka\",env=\"$env\", request=~\"(CreateClusterLinks|DeleteClusterLinks|ListClusterLinks)\", quantile=\"0.99\"}",
     "legendFormat": "{{instance}}-{{request}}"
    }
   ]
  },
  {
   "title": "Remote Time Ms (p99)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_remotetimems{job=\"kafka\",env=\"$env\", request=~\"(CreateClusterLinks|DeleteClusterLinks|ListClusterLinks)\", quantile=\"0.99\"}",
     "legendFormat": "{{instance}}-{{request}}"
    }
   ]
  },
  {
   "title": "Response Send IO Time Ms (p99)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_responsesendiotimems{job=\"kafka\",env=\"$env\", request=~\"(CreateClusterLinks|DeleteClusterLinks|ListClusterLinks)\", quantile=\"0.99\"}",
     "legendFormat": "{{instance}}-{{request}}"
    }
   ]
  },
  {
   "title": "Request Queue Time Ms (p99)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_requestqueuetimems{job=\"kafka\",env=\"$env\", request=~\"(CreateClusterLinks|DeleteClusterLinks|ListClusterLinks)\", quantile=\"0.99\"}",
     "legendFormat": "{{instance}}-{{request}}"
    }
   ]
  },
  {
   "title": "Response Send IO Time Ms (p99)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_responsesendiotimems{job=\"kafka\",env=\"$env\", request=~\"(CreateClusterLinks|DeleteClusterLinks|ListClusterLinks)\", quantile=\"0.99\"}",
     "legendFormat": "{{instance}}-{{request}}"
    }
   ]
  },
  {
   "title": "Response Send Time Ms (p99)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_responsesendtimems{job=\"kafka\",env=\"$env\", request=~\"(CreateClusterLinks|DeleteClusterLinks|ListClusterLinks)\", quantile=\"0.99\"}",
     "legendFormat": "{{instance}}-{{request}}"
    }
   ]
  },
  {
   "title": "Throttle Time Ms (p99)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_throttletimems{job=\"kafka\",env=\"$env\", request=~\"(CreateClusterLinks|DeleteClusterLinks|ListClusterLinks)\", quantile=\"0.99\"}",
     "legendFormat": "{{instance}}-{{request}}"
    }
   ]
  },
  {
   "title": "Request Bytes (p99)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_requestbytes{job=\"kafka\",env=\"$env\", request=~\"(CreateClusterLinks|DeleteClusterLinks|ListClusterLinks)\", quantile=\"0.99\"}",
     "legendFormat": "{{instance}}-{{request}}"
    }
   ]
  },
  {
   "title": "Healthcheck",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster Links count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count(kafka_server_link_clusterlinkfetchermanager_maxlag{job=\"kafka\",env=\"$env\"}) by (linkName))",
       "legendFormat": "Count links"
      }
     ]
    },
    {
     "title": "Mirror Partitions Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kafka_server_cluster_link_metrics_mirror_partition_count{job=\"kafka\",env=\"$env\",linkName=~\"$link_name\"}",
       "legendFormat": "Count links"
      }
     ]
    },
    {
     "title": "Failed Mirror Partitions Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kafka_server_cluster_link_metrics_failed_mirror_partition_count{job=\"kafka\",env=\"$env\",linkName=~\"$link_name\"}",
       "legendFormat": "Count links"
      }
     ]
    },
    {
     "title": "Under Min ISR Mirror Partitions Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kafka_server_replicamanager_underminisrmirrorpartitioncount{job=\"kafka\",env=\"$env\"}",
       "legendFormat": "Count links"
      }
     ]
    },
    {
     "title": "Under Replicated Partitions Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kafka_server_replicamanager_underreplicatedmirrorpartitions{job=\"kafka\",env=\"$env\"}",
       "legendFormat": "Count links"
      }
     ]
    },
    {
     "title": "Blocked Mirror Source Partitions Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kafka_server_replicamanager_blockedonmirrorsourcepartitioncount{job=\"kafka\",env=\"$env\"}",
       "legendFormat": "Count links"
      }
     ]
    },
    {
     "title": "Dead Thread Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kafka_server_link_clusterlinkfetchermanager_deadthreadcount{job=\"kafka\",env=\"$env\",linkName=~\"$link_name\"}",
       "legendFormat": "Count links"
      }
     ]
    },
    {
     "title": "Total Mirror Topic Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kafka_server_cluster_link_metrics_mirror_topic_count{job=\"kafka\", env=\"$env\", link_name=\"$link_name\"})",
       "legendFormat": "Count"
      }
     ]
    },
    {
     "title": "Active Mirror Topic Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kafka_server_cluster_link_metrics_mirror_topic_count{job=\"kafka\", env=\"$env\", link_name=\"$link_name\", state=\"Mirror\"}",
       "legendFormat": "Count"
      }
     ]
    },
    {
     "title": "Paused Mirror Topic Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kafka_server_cluster_link_metrics_mirror_topic_count{job=\"kafka\", env=\"$env\", link_name=\"$link_name\", state=\"PausedMirror\"}",
       "legendFormat": "Count"
      }
     ]
    },
    {
     "title": "Pending Stopped Error Mirror Topic Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kafka_server_cluster_link_metrics_mirror_topic_count{job=\"kafka\", env=\"$env\", link_name=\"$link_name\", state=\"PendingStoppedMirror\"}",
       "legendFormat": "Count"
      }
     ]
    },
    {
     "title": "Stopped Mirror Topic Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kafka_server_cluster_link_metrics_mirror_topic_count{job=\"kafka\", env=\"$env\", link_name=\"$link_name\", state=\"StoppedMirror\"}",
       "legendFormat": "Count"
      }
     ]
    },
    {
     "title": "Topic Mirroring Max Lag",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_server_link_clusterlinkfetchermanager_maxlag{job=\"kafka\",env=\"$env\",linkName=~\"$link_name\"}",
       "legendFormat": "$link_name"
      }
     ]
    },
    {
     "title": "Mirroring Throughput",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "legendFormat": "$link_name" }
     ]
    },
    {
     "title": "Mirroring Request Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "legendFormat": "$link_name" }
     ]
    },
    {
     "title": "(WIP) Mirroring Bytes In",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "kafka_server_fetcherstats_bytespersec_clientid_clusterlinkfetcherthread_0_link_us_to_europe_2_default_brokerhost_broker_us{job=\"kafka\",env=\"$env\", linkName=~\"$link_name\"}",
       "legendFormat": "Bytes In"
      },
      {
       "expr": "kafka_server_cluster_link_fetcher_metrics_outgoing_byte_rate{job=\"kafka\",env=\"$env\", linkName=~\"$link_name\"}",
       "legendFormat": "Bytes Out"
      }
     ]
    },
    {
     "title": "Max Lag",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "records" }
     ],
     "targets": [
      {
       "expr": "kafka_server_link_clusterlinkfetchermanager_maxlag{job=\"kafka\",env=\"$env\", linkName=~\"$link_name\", instance=~\"$instance\"}",
       "legendFormat": "Max Lag"
      },
      {
       "expr": "kafka_server_fetcherstats_bytespersec_clientid_clusterlinkfetcherthread_0_link_us_to_europe_2_default_brokerhost_broker_us{job=\"kafka\",env=\"$env\", linkName=~\"$link_name\", instance=~\"$instance\"}",
       "legendFormat": "Max Lag"
      }
     ]
    }
   ]
  },
  {
   "title": "Destination cluster fetcher throughput metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Throughput",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "kafka_server_cluster_link_fetcher_metrics_incoming_byte_rate{job=\"kafka\",env=\"$env\", linkName=~\"$link_name\"}",
       "legendFormat": "Bytes In"
      },
      {
       "expr": "kafka_server_cluster_link_fetcher_metrics_outgoing_byte_rate{job=\"kafka\",env=\"$env\", linkName=~\"$link_name\"}",
       "legendFormat": "Bytes Out"
      }
     ]
    },
    {
     "title": "Throttle time avg",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_server_cluster_link_fetch_throttle_time_avg{job=\"kafka\",env=\"$env\", linkName=~\"$link_name\", instance=~\"$instance\"}",
       "legendFormat": "Throttle time (avg)"
      },
      {
       "expr": "kafka_server_cluster_link_fetch_throttle_time_max{job=\"kafka\",env=\"$env\", linkName=~\"$link_name\", instance=~\"$instance\"}",
       "legendFormat": "Throttle time (max)"
      }
     ]
    }
   ]
  },
  {
   "title": "Destination cluster fetcher request metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "records/s" }
     ],
     "targets": [
      {
       "expr": "kafka_server_cluster_link_fetcher_metrics_request_rate{job=\"kafka\",env=\"$env\",linkName=~\"$link_name\", instance=~\"$instance\", brokerId=~\"$broker_id\", fetcherId=~\"$fetcher_id\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Request Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "kafka_server_cluster_link_fetcher_metrics_request_size_avg{job=\"kafka\",env=\"$env\",linkName=~\"$link_name\", instance=~\"$instance\", brokerId=~\"$broker_id\", fetcherId=~\"$fetcher_id\"}",
       "legendFormat": "{{instance}} - avg"
      },
      {
       "expr": "kafka_server_cluster_link_fetcher_metrics_request_size_max{job=\"kafka\",env=\"$env\",linkName=~\"$link_name\", instance=~\"$instance\", brokerId=~\"$broker_id\", fetcherId=~\"$fetcher_id\"}",
       "legendFormat": "{{instance}} - max"
      }
     ]
    },
    {
     "title": "Response Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
     "yaxes": [
      { "format": "records/s" }
     ],
     "targets": [
      {
       "expr": "kafka_server_cluster_link_fetcher_metrics_response_rate{job=\"kafka\",env=\"$env\",linkName=~\"$link_name\", instance=~\"$instance\", brokerId=~\"$broker_id\", fetcherId=~\"$fetcher_id\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Destination cluster fetcher connection metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connection Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "connections" }
     ],
     "targets": [
      {
       "expr": "kafka_server_cluster_link_fetcher_metrics_connection_count{job=\"kafka\",env=\"$env\",linkName=~\"$link_name\", instance=~\"$instance\", brokerId=~\"$broker_id\", fetcherId=~\"$fetcher_id\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Connection Creation rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_server_cluster_link_fetcher_metrics_connection_creation_rate{job=\"kafka\",env=\"$env\",linkName=~\"$link_name\", instance=~\"$instance\", brokerId=~\"$broker_id\", fetcherId=~\"$fetcher_id\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Connection Close Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_server_cluster_link_fetcher_metrics_connection_close_rate{job=\"kafka\",env=\"$env\",linkName=~\"$link_name\", instance=~\"$instance\", brokerId=~\"$broker_id\", fetcherId=~\"$fetcher_id\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "IO Ratio",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "kafka_server_cluster_link_fetcher_metrics_io_ratio{job=\"kafka\",env=\"$env\",linkName=~\"$link_name\", instance=~\"$instance\", brokerId=~\"$broker_id\", fetcherId=~\"$fetcher_id\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "IO Wait Time Avg",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "kafka_server_cluster_link_fetcher_metrics_io_wait_time_ns_avg{job=\"kafka\",env=\"$env\",linkName=~\"$link_name\", instance=~\"$instance\", brokerId=~\"$broker_id\", fetcherId=~\"$fetcher_id\"}",
       "legendFormat": "{{instance}}-{{fetcherId}}"
      }
     ]
    },
    {
     "title": "IO Wait Time Avg",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "kafka_server_cluster_link_fetcher_metrics_io_wait_time_ns_avg{job=\"kafka\",env=\"$env\",linkName=~\"$link_name\", instance=~\"$instance\", brokerId=~\"$broker_id\", fetcherId=~\"$fetcher_id\"}",
       "legendFormat": "{{instance}}-{{fetcherId}}"
      }
     ]
    },
    {
     "title": "Network IO Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "kafka_server_cluster_link_fetcher_metrics_network_io_rate{job=\"kafka\",env=\"$env\",linkName=~\"$link_name\", instance=~\"$instance\", brokerId=~\"$broker_id\", fetcherId=~\"$fetcher_id\"}",
       "legendFormat": "{{instance}}-{{fetcherId}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Destination cluster fetcher authentication metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Successful Authentication rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_server_cluster_link_fetcher_metrics_successful_authentication_rate{job=\"kafka\",env=\"$env\",linkName=~\"$link_name\", instance=~\"$instance\", brokerId=~\"$broker_id\", fetcherId=~\"$fetcher_id\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Successful Authentication rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_server_cluster_link_fetcher_metrics_successful_authentication_rate{job=\"kafka\",env=\"$env\",linkName=~\"$link_name\", instance=~\"$instance\", brokerId=~\"$broker_id\", fetcherId=~\"$fetcher_id\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Re-Authentication Latency avg",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_server_cluster_link_fetcher_metrics_reauthentication_latency_avg{job=\"kafka\",env=\"$env\",linkName=~\"$link_name\", instance=~\"$instance\", brokerId=~\"$broker_id\", fetcherId=~\"$fetcher_id\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Destination cluster Cluster link metadata metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Linked Partitions added rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_server_cluster_link_metrics_linked_topic_partition_addition_rate{job=\"kafka\",env=\"$env\",linkName=~\"$link_name\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Consumer Offset committed",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_server_cluster_link_metrics_consumer_offset_committed_rate{job=\"kafka\",env=\"$env\",linkName=~\"$link_name\"}",
       "legendFormat": "{{instance}}-commit success"
      },
      {
       "expr": "kafka_server_cluster_link_metrics_consumer_offset_commit_failed_rate{job=\"kafka\",env=\"$env\",linkName=~\"$link_name\"}",
       "legendFormat": "{{instance}}-commit failed"
      }
     ]
    },
    {
     "title": "Topic update rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_server_cluster_link_metrics_topic_config_update_rate{job=\"kafka\",env=\"$env\",linkName=~\"$link_name\"}",
       "legendFormat": "{{instance}}-topic update success"
      },
      {
       "expr": "kafka_server_cluster_link_metrics_topic_config_update_failed_rate{job=\"kafka\",env=\"$env\",linkName=~\"$link_name\"}",
       "legendFormat": "{{instance}}-topic update failed"
      }
     ]
    },
    {
     "title": "ACL update rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_server_cluster_link_metrics_acls_added_rate{job=\"kafka\",env=\"$env\",linkName=~\"$link_name\"}",
       "legendFormat": "{{instance}}-ACL added success"
      },
      {
       "expr": "kafka_server_cluster_link_metrics_acls_add_failed_rate{job=\"kafka\",env=\"$env\",linkName=~\"$link_name\"}",
       "legendFormat": "{{instance}}-ACL added failure"
      },
      {
       "expr": "kafka_server_cluster_link_metrics_acls_deleted_rate{job=\"kafka\",env=\"$env\",linkName=~\"$link_name\"}",
       "legendFormat": "{{instance}}-ACL deleted success"
      },
      {
       "expr": "kafka_server_cluster_link_metrics_acls_delete_failed_rate{job=\"kafka\",env=\"$env\",linkName=~\"$link_name\"}",
       "legendFormat": "{{instance}}-ACL deleted failed"
      }
     ]
    }
   ]
  }
 ]
}