FROM confluentinc/cp-kafka-connect-base:5.3.1

RUN   confluent-hub install --no-prompt confluentinc/kafka-connect-ibmmq:latest \
		&& confluent-hub install --no-prompt confluentinc/kafka-connect-http:latest \
		&& confluent-hub install --no-prompt debezium/debezium-connector-mysql:latest \
		&& confluent-hub install --no-prompt debezium/debezium-connector-postgresql:latest \
		&& confluent-hub install --no-prompt confluentinc/kafka-connect-elasticsearch:latest \
		&& confluent-hub install --no-prompt wepay/kafka-connect-bigquery:latest \
		&& confluent-hub install --no-prompt confluentinc/kafka-connect-gcs:latest \
		&& confluent-hub install --no-prompt confluentinc/kafka-connect-hdfs:latest \
		&& confluent-hub install --no-prompt confluentinc/kafka-connect-jdbc:latest \
		&& confluent-hub install --no-prompt confluentinc/kafka-connect-kinesis:latest \
		&& confluent-hub install --no-prompt confluentinc/kafka-connect-s3:latest \
		&& confluent-hub install --no-prompt confluentinc/kafka-connect-s3-source:1.1.1-preview \
		&& confluent-hub install --no-prompt confluentinc/kafka-connect-sqs:latest \
		&& confluent-hub install --no-prompt confluentinc/kafka-connect-solace-source:latest \
		&& confluent-hub install --no-prompt confluentinc/kafka-connect-solace-sink:latest \
		&& confluent-hub install --no-prompt debezium/debezium-connector-mongodb:latest \
		&& confluent-hub install --no-prompt confluentinc/kafka-connect-activemq:latest \
		&& confluent-hub install --no-prompt confluentinc/kafka-connect-tibco-source:latest \
		&& confluent-hub install --no-prompt confluentinc/kafka-connect-replicator:latest \
		&& confluent-hub install --no-prompt confluentinc/kafka-connect-syslog:latest \
		&& confluent-hub install --no-prompt splunk/kafka-connect-splunk:latest \
		&& confluent-hub install --no-prompt confluentinc/kafka-connect-tibco-sink:latest \
		&& confluent-hub install --no-prompt confluentinc/kafka-connect-ibmmq-sink:latest \
		&& confluent-hub install --no-prompt confluentinc/kafka-connect-mqtt:latest \
		&& confluent-hub install --no-prompt confluentinc/kafka-connect-jms:latest \
		&& confluent-hub install --no-prompt confluentinc/kafka-connect-influxdb:latest \
		&& confluent-hub install --no-prompt confluentinc/kafka-connect-cassandra:latest \
		&& confluent-hub install --no-prompt confluentinc/kafka-connect-gcp-functions:latest \
		&& confluent-hub install --no-prompt debezium/debezium-connector-sqlserver:latest \
		&& confluent-hub install --no-prompt confluentinc/kafka-connect-activemq-sink:latest \
		&& confluent-hub install --no-prompt confluentinc/kafka-connect-splunk-source:latest \
		&& confluent-hub install --no-prompt confluentinc/kafka-connect-hdfs3:latest \
		&& confluent-hub install --no-prompt confluentinc/kafka-connect-hdfs3-source:latest \
		&& confluent-hub install --no-prompt confluentinc/kafka-connect-aws-cloudwatch-logs:latest \
		&& confluent-hub install --no-prompt confluentinc/kafka-connect-aws-cloudwatch-metrics:latest \
		&& confluent-hub install --no-prompt confluentinc/kafka-connect-aws-dynamodb:latest \
		&& confluent-hub install --no-prompt confluentinc/kafka-connect-aws-lambda:latest \
		&& confluent-hub install --no-prompt confluentinc/kafka-connect-aws-redshift:latest \
		&& confluent-hub install --no-prompt confluentinc/kafka-connect-omnisci:latest \
		&& confluent-hub install --no-prompt confluentinc/kafka-connect-rabbitmq:latest \
		&& confluent-hub install --no-prompt jcustenborder/kafka-connect-spooldir:latest \
		&& confluent-hub install --no-prompt confluentinc/kafka-connect-gcp-pubsub:latest \
		&& confluent-hub install --no-prompt confluentinc/kafka-connect-gcp-spanner:latest \
		&& confluent-hub install --no-prompt confluentinc/kafka-connect-jms-sink:latest \
		&& confluent-hub install --no-prompt confluentinc/kafka-connect-gcs-source:latest \
		&& confluent-hub install --no-prompt confluentinc/kafka-connect-azure-blob-storage:latest \
		&& confluent-hub install --no-prompt confluentinc/kafka-connect-azure-data-lake-gen1-storage:latest \
		&& confluent-hub install --no-prompt confluentinc/kafka-connect-azure-data-lake-gen2-storage:latest \
		&& confluent-hub install --no-prompt confluentinc/kafka-connect-azure-event-hubs:latest \
		&& confluent-hub install --no-prompt confluentinc/kafka-connect-azure-functions:latest \
		&& confluent-hub install --no-prompt neo4j/kafka-connect-neo4j:latest \
		&& wget https://packages.couchbase.com/clients/kafka/3.4.5/kafka-connect-couchbase-3.4.5.zip \
		&& apt-get update && apt-get install unzip \
		&& unzip kafka-connect-couchbase-3.4.5.zip \
		&& mv kafka-connect-couchbase-3.4.5 /usr/share/confluent-hub-components/kafka-connect-couchbase \
		&& confluent-hub install --no-prompt confluentinc/connect-transforms:latest \
		&& confluent-hub install --no-prompt confluentinc/kafka-connect-sftp:latest \
		&& confluent-hub install --no-prompt confluentinc/kafka-connect-hbase:latest \