CREATE USER myuser IDENTIFIED BY mypassword;
GRANT CONNECT TO myuser;
GRANT CREATE SESSION TO myuser;
GRANT CREATE TABLE TO myuser;
GRANT CREATE SEQUENCE TO myuser;
GRANT CREATE TRIGGER TO myuser;
ALTER USER myuser QUOTA 1000M ON users;
ALTER DATABASE default tablespace users;
