{
 "title": "Confluent Cloud",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "topic",
    "label": "Topics",
    "query": {
     "query": "label_values(confluent_kafka_server_retained_bytes, topic)"
    }
   },
   {
    "name": "connector",
    "label": "Connector",
    "query": {
     "query": "label_values(confluent_kafka_connect_connector_status,connector_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Connectors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Connectors",
   "type": "gauge",
   "description": "The number of connectors",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (connector_name) (confluent_kafka_connect_connector_status{connector_name=~\"$connector\"}))"
    }
   ]
  },
  {
   "title": "Total Running Connectors",
   "type": "gauge",
   "description": "The number of connectors",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (connector_name) (confluent_kafka_connect_connector_status{connector_name=~\"$connector\",status=\"RUNNING\"}))"
    }
   ]
  },
  {
   "title": "Total Failed Connectors",
   "type": "gauge",
   "description": "The number of connectors",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (connector_name) (confluent_kafka_connect_connector_status{connector_name=~\"$connector\",status=\"FAILED\"}))"
    }
   ]
  },
  {
   "title": "Total Paused Connectors",
   "type": "gauge",
   "description": "The number of connectors",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (connector_name) (confluent_kafka_connect_connector_status{connector_name=~\"$connector\",status=\"PAUSED\"}))"
    }
   ]
  },
  {
   "title": "Total Degraded Connectors",
   "type": "gauge",
   "description": "The number of connectors",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (connector_name) (confluent_kafka_connect_connector_status{connector_name=~\"$connector\",status=\"DEGRADED\"}))"
    }
   ]
  },
  {
   "title": "Total Restarting Connectors",
   "type": "gauge",
   "description": "The number of connectors",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (connector_name) (confluent_kafka_connect_connector_status{connector_name=~\"$connector\",status=\"RESTARTING\"}))"
    }
   ]
  },
  {
   "title": "Total Provisioning Connectors",
   "type": "gauge",
   "description": "The number of connectors",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (connector_name) (confluent_kafka_connect_connector_status{connector_name=~\"$connector\",status=\"PROVISIONING\"}))"
    }
   ]
  },
  {
   "title": "Connector Status",
   "type": "timeseries",
   "description": "This metric monitors the status of a connector within the system. Its value is always set to 1, signifying the connector's presence. The connector's current operational state is identified through the metric.status tag.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "confluent_kafka_connect_connector_status{connector_name=~\"$connector\"}",
     "legendFormat": "{{connector_name}} ({{connector_id}}, {{plugin_type}}) - {{status}}"
    }
   ]
  },
  {
   "title": "Task Status",
   "type": "timeseries",
   "description": "This metric monitors the status of a connector's task within the system. Its value is always set to 1, signifying the connector task's presence. The connector's current operational state is identified through the metric.status tag.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "confluent_kafka_connect_connector_task_status{connector_name=~\"$connector\"}",
     "legendFormat": "{{connector_name}} ({{connector_id}}, {{plugin_type}}) - {{status}}"
    }
   ]
  },
  {
   "title": "Sent records",
   "type": "timeseries",
   "description": "The delta count of total number of records sent from the transformations and written to Kafka for the source connector. Each sample is the number of records sent since the previous data point. The count is sampled every 60 seconds.",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "confluent_kafka_connect_sent_records{connector_name=~\"$connector\"}",
     "legendFormat": "{{connector_name}} ({{connector_id}})"
    }
   ]
  },
  {
   "title": "Received records",
   "type": "timeseries",
   "description": "The delta count of total number of records received by the sink connector. Each sample is the number of records received since the previous data point. The count is sampled every 60 seconds.",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "confluent_kafka_connect_received_records{connector_name=~\"$connector\"}",
     "legendFormat": "{{connector_name}} ({{connector_id}})"
    }
   ]
  },
  {
   "title": "Dead Letter Queue records",
   "type": "timeseries",
   "description": "The delta count of dead letter queue records written to Kafka for the sink connector. The count is sampled every 60 seconds.",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "confluent_kafka_connect_dead_letter_queue_records{connector_name=~\"$connector\"}",
     "legendFormat": "{{connector_name}} ({{connector_id}})"
    }
   ]
  },
  {
   "title": "Sent bytes",
   "type": "timeseries",
   "description": "The delta count of total bytes sent from the transformations and written to Kafka for the source connector. Each sample is the number of bytes sent since the previous data point. The count is sampled every 60 seconds.",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "confluent_kafka_connect_sent_bytes{connector_name=~\"$connector\"}",
     "legendFormat": "{{connector_name}} ({{connector_id}})"
    }
   ]
  },
  {
   "title": "Received bytes",
   "type": "timeseries",
   "description": "The delta count of total bytes received by the sink connector. Each sample is the number of bytes received since the previous data point. The count is sampled every 60 seconds.",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "confluent_kafka_connect_received_bytes{connector_name=~\"$connector\"}",
     "legendFormat": "{{connector_name}} ({{connector_id}})"
    }
   ]
  },
  {
   "title": "Records Lag Max",
   "type": "timeseries",
   "description": "The max number of records the sink connector is behind among all partitions. The count is sampled every 60 seconds.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "confluent_kafka_connect_records_lag_max{connector_name=~\"$connector\"}",
     "legendFormat": "{{connector_name}} ({{connector_id}})"
    }
   ]
  },
  {
   "title": "Batch Size Avg",
   "type": "timeseries",
   "description": "Monitors the average batch size (measured by record count) per minute. For a source connector, it indicates the average batch size sent to Kafka. For a sink connector, it indicates the average batch size read by the sink task.",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "confluent_kafka_connect_connector_task_batch_size_avg{connector_name=~\"$connector\"}",
     "legendFormat": "{{connector_name}} ({{connector_id}})"
    }
   ]
  },
  {
   "title": "Batch Size Max",
   "type": "timeseries",
   "description": "Monitors the maximum batch size (measured by record count) per minute. For a source connector, it indicates the max batch size sent to Kafka. For a sink connector, it indicates the max batch size read by the sink task.",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "confluent_kafka_connect_connector_task_batch_size_max{connector_name=~\"$connector\"}",
     "legendFormat": "{{connector_name}} ({{connector_id}})"
    }
   ]
  },
  {
   "title": "Sink Task put batch Avg",
   "type": "timeseries",
   "description": "The average time it takes to put a batch of records to the sink. The average is calculated per minute.",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "confluent_kafka_connect_sink_task_put_batch_avg_time_milliseconds{connector_name=~\"$connector\"}",
     "legendFormat": "{{connector_name}} ({{connector_id}})"
    }
   ]
  },
  {
   "title": "Sink Task put batch Max",
   "type": "timeseries",
   "description": "The maximum time it takes to put a batch of records to the sink. The max is calculated per minute.",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "confluent_kafka_connect_sink_task_put_batch_max_time_milliseconds{connector_name=~\"$connector\"}",
     "legendFormat": "{{connector_name}} ({{connector_id}})"
    }
   ]
  },
  {
   "title": "Consumer Lag Offsets",
   "type": "timeseries",
   "description": "The lag between a group member's committed offset and the partition's high watermark.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "sum by (consumer_group_id, topic) (confluent_kafka_server_consumer_lag_offsets{topic=~\"$topic\"})",
     "legendFormat": "{{topic}}-{{consumer_group_id}}"
    }
   ]
  },
  {
   "title": "Connectors - MySQL CDC source V2",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "panels": [
    {
     "title": "Lag",
     "type": "timeseries",
     "description": "It is applicable only for MySQL CDC source V2 connector. It represents the number of milliseconds between the last change event’s timestamp and the connector processing it. The values will incorporate any differences between the clocks on the machines where the database server and the connector are running.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "confluent_kafka_connect_mysql_cdc_source_connector_lag_milliseconds{connector_name=~\"$connector\"}",
       "legendFormat": "{{connector_name}} ({{connector_id}})"
      }
     ]
    },
    {
     "title": "Number of Events Seen",
     "type": "timeseries",
     "description": "It is applicable only for MySQL CDC source V2 connector. It represents the total number of events that this connector has seen since last started or reset. The values will incorporate any differences between the clocks on the machines where the database server and the connector are running.",
     "gridPos": { "h": 8, "w": 8, "x": 6, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "confluent_kafka_connect_mysql_cdc_source_connector_streaming_total_number_of_events_seen{connector_name=~\"$connector\"}",
       "legendFormat": "{{connector_name}} ({{connector_id}})"
      }
     ]
    },
    {
     "title": "Snapshot running",
     "type": "timeseries",
     "description": "It is applicable only for MySQL CDC source connector. It represents whether the Snapshot is running. The values will incorporate any differences between the clocks on the machines where the database server and the connector are running.",
     "gridPos": { "h": 8, "w": 5, "x": 14, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "confluent_kafka_connect_mysql_cdc_source_connector_snapshot_running{connector_name=~\"$connector\"}",
       "legendFormat": "{{connector_name}} ({{connector_id}})"
      }
     ]
    },
    {
     "title": "Snapshot completed",
     "type": "timeseries",
     "description": "It is applicable only for MySQL CDC source connector. It represents whether the Snapshot is completed. The values will incorporate any differences between the clocks on the machines where the database server and the connector are running.",
     "gridPos": { "h": 8, "w": 5, "x": 19, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "confluent_kafka_connect_mysql_cdc_source_connector_snapshot_completed{connector_name=~\"$connector\"}",
       "legendFormat": "{{connector_name}} ({{connector_id}})"
      }
     ]
    },
    {
     "title": "Number of Committed transactions",
     "type": "timeseries",
     "description": "It is applicable only for MySQL CDC source V2 connector. It represents the number of processed transactions that were committed. The values will incorporate any differences between the clocks on the machines where the database server and the connector are running.",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "confluent_kafka_connect_mysql_cdc_source_connector_streaming_number_of_committed_transactions{connector_name=~\"$connector\"}",
       "legendFormat": "{{connector_name}} ({{connector_id}})"
      }
     ]
    },
    {
     "title": "Number of Rollbacked transactions",
     "type": "timeseries",
     "description": "It is applicable only for MySQL CDC source V2 connector. It represents the number of processed transactions that were rolled back and not streamed. The values will incorporate any differences between the clocks on the machines where the database server and the connector are running.",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "confluent_kafka_connect_mysql_cdc_source_connector_streaming_number_of_rolled_back_transactions{connector_name=~\"$connector\"}",
       "legendFormat": "{{connector_name}} ({{connector_id}})"
      }
     ]
    },
    {
     "title": "Number of Skipped events",
     "type": "timeseries",
     "description": "It is applicable only for MySQL CDC source V2 connector. It represents the number of events that have been skipped by the connector. The values will incorporate any differences between the clocks on the machines where the database server and the connector are running.",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "confluent_kafka_connect_mysql_cdc_source_connector_streaming_number_of_skipped_events{connector_name=~\"$connector\"}",
       "legendFormat": "{{connector_name}} ({{connector_id}})"
      }
     ]
    },
    {
     "title": "Number of large transactions",
     "type": "timeseries",
     "description": "It is applicable only for MySQL CDC source V2 connector. It represents the number of transactions that have not fit into the look-ahead buffer. The values will incorporate any differences between the clocks on the machines where the database server and the connector are running.",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "confluent_kafka_connect_mysql_cdc_source_connector_streaming_number_of_large_transactions{connector_name=~\"$connector\"}",
       "legendFormat": "{{connector_name}} ({{connector_id}})"
      }
     ]
    },
    {
     "title": "Schema History status",
     "type": "timeseries",
     "description": "It is applicable only for MySQL CDC source connector. It represents the status of the schema history of the connector. The values will incorporate any differences between the clocks on the machines where the database server and the connector are running.",
     "gridPos": { "h": 8, "w": 4, "x": 16, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "confluent_kafka_connect_mysql_cdc_source_connector_schema_history_status{connector_name=~\"$connector\"}",
       "legendFormat": "{{connector_name}} ({{connector_id}})"
      }
     ]
    },
    {
     "title": "Number of Disconnects",
     "type": "stat",
     "description": "It is applicable only for MySQL CDC source V2 connector. It represents the number of disconnects by the connector. The values will incorporate any differences between the clocks on the machines where the database server and the connector are running.",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "confluent_kafka_connect_mysql_cdc_source_connector_streaming_number_of_disconnects{connector_name=~\"$connector\"}",
       "legendFormat": "{{connector_name}} ({{connector_id}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Connectors - Postgres CDC source V2",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true,
   "panels": [
    {
     "title": "Lag",
     "type": "timeseries",
     "description": "It is applicable only for Postgres CDC source V2 connector. It represents the number of milliseconds between the last change event’s timestamp and the connector processing it. The values will incorporate any differences between the clocks on the machines where the database server and the connector are running.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "confluent_kafka_connect_postgres_cdc_source_connector_lag_milliseconds{connector_name=~\"$connector\"}",
       "legendFormat": "{{connector_name}} ({{connector_id}})"
      }
     ]
    },
    {
     "title": "Number of Events Seen",
     "type": "timeseries",
     "description": "It is applicable only for Postgres CDC source V2 connector. It represents the total number of events that this connector has seen since last started or reset. The values will incorporate any differences between the clocks on the machines where the database server and the connector are running.",
     "gridPos": { "h": 8, "w": 8, "x": 6, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "confluent_kafka_connect_postgres_cdc_source_connector_streaming_total_number_of_events_seen{connector_name=~\"$connector\"}",
       "legendFormat": "{{connector_name}} ({{connector_id}})"
      }
     ]
    },
    {
     "title": "Snapshot running",
     "type": "timeseries",
     "description": "It is applicable only for Postgres CDC source connector. It represents whether the Snapshot is running. The values will incorporate any differences between the clocks on the machines where the database server and the connector are running.",
     "gridPos": { "h": 8, "w": 5, "x": 14, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "confluent_kafka_connect_postgres_cdc_source_connector_snapshot_running{connector_name=~\"$connector\"}",
       "legendFormat": "{{connector_name}} ({{connector_id}})"
      }
     ]
    },
    {
     "title": "Snapshot completed",
     "type": "timeseries",
     "description": "It is applicable only for Postgres CDC source connector. It represents whether the Snapshot is completed. The values will incorporate any differences between the clocks on the machines where the database server and the connector are running.",
     "gridPos": { "h": 8, "w": 5, "x": 19, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "confluent_kafka_connect_postgres_cdc_source_connector_snapshot_completed{connector_name=~\"$connector\"}",
       "legendFormat": "{{connector_name}} ({{connector_id}})"
      }
     ]
    },
    {
     "title": "Number of Committed transactions",
     "type": "timeseries",
     "description": "It is applicable only for Postgres CDC source V2 connector. It represents the number of processed transactions that were committed. The values will incorporate any differences between the clocks on the machines where the database server and the connector are running.",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "confluent_kafka_connect_postgres_cdc_source_connector_streaming_number_of_committed_transactions{connector_name=~\"$connector\"}",
       "legendFormat": "{{connector_name}} ({{connector_id}})"
      }
     ]
    },
    {
     "title": "Number of Rollbacked transactions",
     "type": "timeseries",
     "description": "It is applicable only for Postgres CDC source V2 connector. It represents the number of processed transactions that were rolled back and not streamed. The values will incorporate any differences between the clocks on the machines where the database server and the connector are running.",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "confluent_kafka_connect_postgres_cdc_source_connector_streaming_number_of_rolled_back_transactions{connector_name=~\"$connector\"}",
       "legendFormat": "{{connector_name}} ({{connector_id}})"
      }
     ]
    },
    {
     "title": "Number of Skipped events",
     "type": "timeseries",
     "description": "It is applicable only for Postgres CDC source V2 connector. It represents the number of events that have been skipped by the connector. The values will incorporate any differences between the clocks on the machines where the database server and the connector are running.",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "confluent_kafka_connect_postgres_cdc_source_connector_streaming_number_of_skipped_events{connector_name=~\"$connector\"}",
       "legendFormat": "{{connector_name}} ({{connector_id}})"
      }
     ]
    },
    {
     "title": "Number of large transactions",
     "type": "timeseries",
     "description": "It is applicable only for Postgres CDC source V2 connector. It represents the number of transactions that have not fit into the look-ahead buffer. The values will incorporate any differences between the clocks on the machines where the database server and the connector are running.",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "confluent_kafka_connect_postgres_cdc_source_connector_streaming_number_of_large_transactions{connector_name=~\"$connector\"}",
       "legendFormat": "{{connector_name}} ({{connector_id}})"
      }
     ]
    },
    {
     "title": "Schema History status",
     "type": "timeseries",
     "description": "It is applicable only for Postgres CDC source connector. It represents the status of the schema history of the connector. The values will incorporate any differences between the clocks on the machines where the database server and the connector are running.",
     "gridPos": { "h": 8, "w": 4, "x": 16, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "confluent_kafka_connect_postgres_cdc_source_connector_schema_history_status{connector_name=~\"$connector\"}",
       "legendFormat": "{{connector_name}} ({{connector_id}})"
      }
     ]
    },
    {
     "title": "Number of Disconnects",
     "type": "stat",
     "description": "It is applicable only for Postgres CDC source V2 connector. It represents the number of disconnects by the connector. The values will incorporate any differences between the clocks on the machines where the database server and the connector are running.",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "confluent_kafka_connect_postgres_cdc_source_connector_streaming_number_of_disconnects{connector_name=~\"$connector\"}",
       "legendFormat": "{{connector_name}} ({{connector_id}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Kafka Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Retained bytes ",
   "type": "stat",
   "description": "Basic clusters have a max retained bytes limit of 5 TB prior to replication. ccloud_metrics_retained_bytes is after replication thus needs to be divided by 3.",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(confluent_kafka_server_retained_bytes{topic=~\"$topic\"})/3",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Write on topics (rate)",
   "type": "stat",
   "description": "Per-second average rate of ingress of data to topics, basic cluster has a max of 100MBps.",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(confluent_kafka_server_received_bytes{topic=~\"$topic\"}[1m]))",
     "legendFormat": "{{kafka_id}}"
    }
   ]
  },
  {
   "title": "Read of topics (rate)",
   "type": "stat",
   "description": "Per-second average rate of egress data to topics, basic cluster has a max of 100MBps.",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(confluent_kafka_server_sent_bytes{topic=~\"$topic\"}[1m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Request Count (rate)",
   "type": "stat",
   "description": "Per-second average rate of requests, basic cluster maxes out at 1500 requests per second.",
   "gridPos": { "h": 5, "w": 4, "x": 13, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(confluent_kafka_server_request_count{type=~\".*\"}[1m]))",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Avg. Active connections",
   "type": "stat",
   "description": "The average active connections to a cluster. Basic clusters limit active connections to 1000.",
   "gridPos": { "h": 5, "w": 4, "x": 17, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "avg(confluent_kafka_server_active_connection_count)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Total Schemas",
   "type": "gauge",
   "description": "The number of registered schemas",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "confluent_kafka_schema_registry_schema_count",
     "legendFormat": "{{schema_registry_id}}"
    }
   ]
  },
  {
   "title": "Partition count change (delta)",
   "type": "timeseries",
   "description": "Basic clusters have a limit on the number of partitions that can be created and deleted in a 5 minute period. This single stat provides the absolute difference between the number of partitions are the beginning and end of the 5 minute period. This over simplifies the problem, so more conservative thresholds are put in place. ",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "abs(delta(confluent_kafka_server_partition_count[5m]))",
     "legendFormat": "{{kafka_id}}"
    }
   ]
  },
  {
   "title": "Partition count ",
   "type": "timeseries",
   "description": "The sum of partitions in a cluster. Basic cluster max partitions limit is 2048.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "confluent_kafka_server_partition_count",
     "legendFormat": "{{kafka_id}}"
    }
   ]
  },
  {
   "title": "Authentication Rate",
   "type": "timeseries",
   "description": "The average authentication rate",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "confluent_kafka_server_successful_authentication_count{}",
     "legendFormat": "{{principal_id}}"
    }
   ]
  },
  {
   "title": "Topics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Topic retained bytes",
   "type": "timeseries",
   "description": "The current count of bytes retained by the cluster, summed across all partitions. The count is sampled every 60 seconds.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (kafka_id, topic) (confluent_kafka_server_retained_bytes{topic=~\"$topic\"})",
     "legendFormat": "{{kafka_id}}-{{topic}}"
    }
   ]
  },
  {
   "title": "Topic received bytes",
   "type": "timeseries",
   "description": "The delta count of bytes received from the network. Each sample is the number of bytes received since the previous data sample. The count is sampled every 60 seconds.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (topic, kafka_id) (confluent_kafka_server_received_bytes{topic=~\"$topic\"})",
     "legendFormat": "{{topic}} - {{kafka_id}}"
    }
   ]
  },
  {
   "title": "Topic Sent bytes",
   "type": "timeseries",
   "description": "The delta count of bytes sent over the network. Each sample is the number of bytes sent since the previous data point. The count is sampled every 60 seconds.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (topic, kafka_id) (confluent_kafka_server_sent_bytes{topic=~\"$topic\"})",
     "legendFormat": "{{topic}} - {{kafka_id}}"
    }
   ]
  },
  {
   "title": "Topic received record",
   "type": "timeseries",
   "description": "The delta count of records received. Each sample is the number of records received since the previous data sample. The count is sampled every 60 seconds.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (topic, kafka_id) (confluent_kafka_server_received_records{topic=~\"$topic\"})",
     "legendFormat": "{{topic}} - {{kafka_id}}"
    }
   ]
  },
  {
   "title": "Topic sent records",
   "type": "timeseries",
   "description": "The delta count of records sent. Each sample is the number of records sent since the previous data point. The count is sampled every 60 seconds.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (topic, kafka_id) (confluent_kafka_server_sent_records{topic=~\"$topic\"})",
     "legendFormat": "{{topic}} - {{kafka_id}}"
    }
   ]
  },
  {
   "title": "Request rate",
   "type": "timeseries",
   "description": "The delta count of requests received over the network. Each sample is the number of requests received since the previous data point. The count sampled every 60 seconds.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "confluent_kafka_server_request_count",
     "legendFormat": "{{kafka_id}}-{{type}}"
    }
   ]
  },
  {
   "title": "Metrics API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 111 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Scrape duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "scrape_duration_seconds{job=\"Confluent Cloud\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}