cd ${root_folder}/scripts/cli

docker run --rm -i --user $(id -u):$(id -g) --volume "$PWD:/app" dannyben/bashly render templates/markdown docs

cat ${root_folder}/scripts/cli/docs-template/cli-template.md > ${root_folder}/docs/cli.md
cat ${root_folder}/scripts/cli/docs/index.md >> ${root_folder}/docs/cli.md

# list of CLI reference pages, indexed by the search plugin of the documentation website (see index.html in kafka-docker-playground-docs)
{
  echo "// generated by 'playground update-docs' in https://github.com/vdesabou/kafka-docker-playground: list of CLI reference pages, indexed by the search plugin"
  echo "window.KDP_CLI_PAGES = ["
  ls ${root_folder}/scripts/cli/docs | grep '^playground .*\.md$' | sed -e 's/\.md$//' -e 's/ /%20/g' -e 's#.*#  "/&",#'
  echo "];"
} > ${root_folder}/docs/cli-pages.js

mv ${root_folder}/scripts/cli/docs/* ${root_folder}/docs/