apiVersion: platform.confluent.io/v1beta1
kind: Connector
metadata:
  name: http-sink
  namespace: confluent
spec:
  taskMax: 1
  class: io.confluent.connect.http.HttpSinkConnector
  connectClusterRef:
    name: connect
  configs:
    topics: http-messages
    tasks.max: "1"
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter.schemas.enable: "false"
    confluent.topic.bootstrap.servers: kafka:9071
    confluent.topic.replication.factor: "1"
    reporter.bootstrap.servers: kafka:9071
    reporter.error.topic.name: error-responses
    reporter.error.topic.replication.factor: "1"
    reporter.result.topic.name: success-responses
    reporter.result.topic.replication.factor: "1"
    reporter.result.topic.value.format: string
    http.api.url: http://httpserver:9006
    request.body.format: json
    headers: "Content-Type: application/json"