---
services:

  rabbitmq:
    image: rabbitmq:3.8.19-alpine
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - "5671:5671"
      - "5672:5672"
      - "8080:8080"
    environment:
      RABBITMQ_DEFAULT_USER: "myuser"
      RABBITMQ_DEFAULT_PASS: "mypassword"

  rabbitmq-producer:
    build:
      context: ../../connect/connect-rabbitmq-source/producer
    hostname: rabbitmq-producer
    container_name: rabbitmq-producer

  rabbitmq-consumer:
    build:
      context: ../../connect/connect-rabbitmq-source/consumer
    hostname: rabbitmq-consumer
    container_name: rabbitmq-consumer

  connect:
    depends_on:
      - rabbitmq
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-rabbitmq
      CONNECT_LOG4J_LOGGERS: org.apache.zookeeper=ERROR,org.I0Itec.zkclient=ERROR,org.reflections=ERROR,com.rabbitmq.client=TRACE