FROM mongo
    
RUN apt-get update \
  && apt-get install -y --no-install-recommends build-essential python3-pip python3-setuptools python3-dev \
  && rm -rf /var/lib/apt/lists/*

RUN pip3 install mtools[all]

CMD ["mlaunch"]