echo 'Creating CUSTOMERS table'

sqlplus MYUSER/password@//localhost:1521/XE  <<- EOF

create table CUSTOMERS (
        "XREG_DISTRIBUIDO" NUMBER(5,0) DEFAULT 0,
        "XDESCRIPCION" VARCHAR2(60 BYTE) NOT NULL ENABLE,
        "XSUBTIPO_CLASE" NUMBER(5,0), 
        "XSUBTIPO_ID" VARCHAR2(25 BYTE) NOT NULL PRIMARY KEY ENABLE,
        "XFECHA_ALTA" DATE, "XFECHA_MODIF" DATE,
        "XUSUARIO_ALTA" VARCHAR2(18 BYTE), 
        "XUSUARIO_MODIF" VARCHAR2(18 BYTE)
);

ALTER TABLE CUSTOMERS ADD (
  CONSTRAINT CUSTOMERS_PK PRIMARY KEY (XSUBTIPO_ID));
/
EOF