sqlplus MYUSER/password@//localhost:1521/XE  <<- EOF

INSERT INTO CUSTOMERS ( XREG_DISTRIBUIDO, XDESCRIPCION, XSUBTIPO_CLASE, XSUBTIPO_ID, XFECHA_ALTA, XFECHA_MODIF, XUSUARIO_ALTA, XUSUARIO_MODIF) VALUES ('1','Prueba RRR','1','P_RR1',sysdate,'','Vincent','Vincent');
INSERT INTO CUSTOMERS ( XREG_DISTRIBUIDO, XDESCRIPCION, XSUBTIPO_CLASE, XSUBTIPO_ID, XFECHA_ALTA, XFECHA_MODIF, XUSUARIO_ALTA, XUSUARIO_MODIF) VALUES ('1','Prueba RRR','1','P_RR2',sysdate,'','Vincent','Vincent');
INSERT INTO CUSTOMERS ( XREG_DISTRIBUIDO, XDESCRIPCION, XSUBTIPO_CLASE, XSUBTIPO_ID, XFECHA_ALTA, XFECHA_MODIF, XUSUARIO_ALTA, XUSUARIO_MODIF) VALUES ('1','Prueba RRR','1','P_RR3',sysdate,'','Vincent','Vincent');
INSERT INTO CUSTOMERS ( XREG_DISTRIBUIDO, XDESCRIPCION, XSUBTIPO_CLASE, XSUBTIPO_ID, XFECHA_ALTA, XFECHA_MODIF, XUSUARIO_ALTA, XUSUARIO_MODIF) VALUES ('1','Prueba RRR','1','P_RR4',sysdate,'','Vincent','Vincent');
INSERT INTO CUSTOMERS ( XREG_DISTRIBUIDO, XDESCRIPCION, XSUBTIPO_CLASE, XSUBTIPO_ID, XFECHA_ALTA, XFECHA_MODIF, XUSUARIO_ALTA, XUSUARIO_MODIF) VALUES ('1','Prueba RRR','1','P_RR5',sysdate,'','Vincent','Vincent');
EOF