---
services:

  elasticsearch:
    image: elasticsearch:9.3.0
    hostname: elasticsearch
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    command:
      - elasticsearch
      - -Ediscovery.type=single-node
      - -Expack.security.enabled=false
      - -Expack.security.http.ssl.enabled=false
      
  connect:
    depends_on:
      - elasticsearch
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-http