---
services:

  sfdx-cli:
    # forked from salestrip/sfdx-cli to add plugin sfpowerkit
    image: vdesabou/sfdx-cli:latest
    hostname: sfdx-cli
    container_name: sfdx-cli
    entrypoint: ["sh", "-c", "sleep infinity"]

  connect:
    volumes:
      - ../../connect/connect-salesforce-cdc-source/salesforce-confluent.keystore.jks:/tmp/salesforce-confluent.keystore.jks
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-salesforce