{
 "title": "Confluent Cloud",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(ccloud_metric_retained_bytes, cluster_id)"
   },
   {
    "name": "topic",
    "label": "Topics",
    "query": "label_values(ccloud_metric_retained_bytes, topic)"
   }
  ]
 },
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Partition count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(ccloud_metric_partition_count{cluster_id=~\"$cluster\"})",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Current topic bytes retained",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "targets": [
    {
     "expr": "sum(ccloud_metric_retained_bytes{topic=~\"$topic\", cluster_id=~\"$cluster\"})",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Current read of topics ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sum(ccloud_metric_sent_bytes{topic=~\"$topic\", cluster_id=~\"$cluster\"})",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Write on topics (avg)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "sum(ccloud_metric_received_bytes{topic=~\"$topic\", cluster_id=~\"$cluster\"})",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Read of topics (avg)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(ccloud_metric_sent_bytes{topic=~\"$topic\", cluster_id=~\"$cluster\"})",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Current write on topics",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "targets": [
    {
     "expr": "sum(ccloud_metric_received_bytes{topic=~\"$topic\", cluster_id=~\"$cluster\"})",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Active connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "avg(ccloud_metric_active_connection_count{cluster_id=~\"$cluster\"})",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Metrics API latency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "targets": [
    {
     "expr": "avg(ccloud_metrics_api_request_latency)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  { "title": "Topics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Topic retained bytes",
   "type": "graph",
   "description": "The current count of bytes retained by the cluster, summed across all partitions. The count is sampled every 60 seconds.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (cluster_id, topic) (ccloud_metric_retained_bytes{topic=~\"$topic\", cluster_id=~\"$cluster\"})",
     "legendFormat": "{{cluster_id}}-{{topic}}"
    }
   ]
  },
  {
   "title": "Topic received bytes",
   "type": "graph",
   "description": "The delta count of bytes received from the network. Each sample is the number of bytes received since the previous data sample. The count is sampled every 60 seconds.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (topic, cluster_id) (ccloud_metric_received_bytes{topic=~\"$topic\", cluster_id=~\"$cluster\"})",
     "legendFormat": "{{topic}} - {{cluster_id}}"
    }
   ]
  },
  {
   "title": "Topic Sent bytes",
   "type": "graph",
   "description": "The delta count of bytes sent over the network. Each sample is the number of bytes sent since the previous data point. The count is sampled every 60 seconds.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (topic, cluster_id) (ccloud_metric_sent_bytes{topic=~\"$topic\", cluster_id=~\"$cluster\"})",
     "legendFormat": "{{topic}} - {{cluster_id}}"
    }
   ]
  },
  {
   "title": "Topic received record",
   "type": "graph",
   "description": "The delta count of records received. Each sample is the number of records received since the previous data sample. The count is sampled every 60 seconds.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (topic, cluster_id) (ccloud_metric_received_records{topic=~\"$topic\", cluster_id=~\"$cluster\"})",
     "legendFormat": "{{topic}} - {{cluster_id}}"
    }
   ]
  },
  {
   "title": "Topic sent records",
   "type": "graph",
   "description": "The delta count of records sent. Each sample is the number of records sent since the previous data point. The count is sampled every 60 seconds.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (topic, cluster_id) (ccloud_metric_sent_records{topic=~\"$topic\", cluster_id=~\"$cluster\"})",
     "legendFormat": "{{topic}} - {{cluster_id}}"
    }
   ]
  },
  {
   "title": "Request rate",
   "type": "graph",
   "description": "The delta count of requests received over the network. Each sample is the number of requests received since the previous data point. The count sampled every 60 seconds.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ccloud_metric_request_count{cluster_id=~\"$cluster\"}",
     "legendFormat": "{{cluster_id}}-{{type}}"
    }
   ]
  },
  { "title": "Metrics API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Metrics API latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ccloud_metrics_api_request_latency",
     "legendFormat": "{{metric}}"
    }
   ]
  },
  {
   "title": "Scrape duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "scrape_duration_seconds{job=\"ccloudexporter\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}