{
 "title": "Dotnet Consumer",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "All Consumer Lags",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "librdkafka_consumer_lag" }
   ]
  },
  {
   "title": "Number of pre-fetched messages in fetch queue",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "librdkafka_fetch_queue_count" }
   ]
  },
  {
   "title": "Size of fetch queue",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "librdkafka_fetch_queue_size" }
   ]
  },
  {
   "title": "Rate of messages consumed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(librdkafka_messages_consumed{job=\"dotnet-consumer\", topic!=\"\"}[1m])) by (topic)"
    }
   ]
  },
  {
   "title": "Rate of bytes consumed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(librdkafka_bytes_consumed{job=\"dotnet-consumer\", topic!=\"\"}[1m])) by (topic)"
    }
   ]
  }
 ]
}