---
# Confluent Telemetry Reporter (proactive support / Health+)
# Automatically added by environment start.sh scripts when CONFLUENT_CLOUD_API_KEY and CONFLUENT_CLOUD_API_SECRET are set
# (see determine_confluent_telemetry in scripts/cli/src/lib/utils_function.sh)
services:

  broker:
    environment:
      KAFKA_CONFLUENT_TELEMETRY_ENABLED: 'true'
      KAFKA_CONFLUENT_TELEMETRY_API_KEY: ${CONFLUENT_CLOUD_API_KEY}
      KAFKA_CONFLUENT_TELEMETRY_API_SECRET: ${CONFLUENT_CLOUD_API_SECRET}

  broker2:
    environment:
      KAFKA_CONFLUENT_TELEMETRY_ENABLED: 'true'
      KAFKA_CONFLUENT_TELEMETRY_API_KEY: ${CONFLUENT_CLOUD_API_KEY}
      KAFKA_CONFLUENT_TELEMETRY_API_SECRET: ${CONFLUENT_CLOUD_API_SECRET}

  broker3:
    environment:
      KAFKA_CONFLUENT_TELEMETRY_ENABLED: 'true'
      KAFKA_CONFLUENT_TELEMETRY_API_KEY: ${CONFLUENT_CLOUD_API_KEY}
      KAFKA_CONFLUENT_TELEMETRY_API_SECRET: ${CONFLUENT_CLOUD_API_SECRET}

  schema-registry:
    environment:
      SCHEMA_REGISTRY_METRIC_REPORTERS: io.confluent.telemetry.reporter.TelemetryReporter
      SCHEMA_REGISTRY_CONFLUENT_TELEMETRY_ENABLED: 'true'
      SCHEMA_REGISTRY_CONFLUENT_TELEMETRY_API_KEY: ${CONFLUENT_CLOUD_API_KEY}
      SCHEMA_REGISTRY_CONFLUENT_TELEMETRY_API_SECRET: ${CONFLUENT_CLOUD_API_SECRET}

  connect:
    environment:
      CONNECT_METRIC_REPORTERS: io.confluent.telemetry.reporter.TelemetryReporter
      CONNECT_CONFLUENT_TELEMETRY_ENABLED: 'true'
      CONNECT_CONFLUENT_TELEMETRY_API_KEY: ${CONFLUENT_CLOUD_API_KEY}
      CONNECT_CONFLUENT_TELEMETRY_API_SECRET: ${CONFLUENT_CLOUD_API_SECRET}

  connect2:
    environment:
      CONNECT_METRIC_REPORTERS: io.confluent.telemetry.reporter.TelemetryReporter
      CONNECT_CONFLUENT_TELEMETRY_ENABLED: 'true'
      CONNECT_CONFLUENT_TELEMETRY_API_KEY: ${CONFLUENT_CLOUD_API_KEY}
      CONNECT_CONFLUENT_TELEMETRY_API_SECRET: ${CONFLUENT_CLOUD_API_SECRET}

  connect3:
    environment:
      CONNECT_METRIC_REPORTERS: io.confluent.telemetry.reporter.TelemetryReporter
      CONNECT_CONFLUENT_TELEMETRY_ENABLED: 'true'
      CONNECT_CONFLUENT_TELEMETRY_API_KEY: ${CONFLUENT_CLOUD_API_KEY}
      CONNECT_CONFLUENT_TELEMETRY_API_SECRET: ${CONFLUENT_CLOUD_API_SECRET}

  ksqldb-server:
    environment:
      KSQL_METRIC_REPORTERS: io.confluent.telemetry.reporter.TelemetryReporter
      KSQL_CONFLUENT_TELEMETRY_ENABLED: 'true'
      KSQL_CONFLUENT_TELEMETRY_API_KEY: ${CONFLUENT_CLOUD_API_KEY}
      KSQL_CONFLUENT_TELEMETRY_API_SECRET: ${CONFLUENT_CLOUD_API_SECRET}
