{
 "title": "Mongo connector",
 "description": "Monitor Mongo connector",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment",
    "query": {
     "query": "label_values(kafka_connect_app_info,env)"
    }
   },
   {
    "name": "kafka_connect_cluster_id",
    "label": "Cluster ID",
    "query": {
     "query": "label_values(kafka_connect_app_info,kafka_connect_cluster_id)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(kafka_connect_app_info{job=\"kafka-connect\", env=\"$env\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\"},instance)"
    }
   },
   {
    "name": "connector",
    "label": "Connector name",
    "query": {
     "query": "label_values(kafka_connect_connector_task_metrics_pause_ratio{job=\"kafka-connect\", env=\"$env\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\"},connector)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Mongo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Records",
   "type": "stat",
   "description": "\t\nThe total number of records a MongoDB source task passed to the Kafka Connect framework.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_connect_mongodb_source_task_metrics_records{job=\"kafka-connect\", env=\"$env\",instance=~\"$instance\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",connector=~\"$connector\",task=~\"source-task-0\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Records",
   "type": "timeseries",
   "description": "records\nThe total number of records a MongoDB source task passed to the Kafka Connect framework.\n\nrecords-filtered\nThe number of records a MongoDB source task passed to the Kafka Connect framework that were then filtered by the framework. A filtered record is not written to Kafka.\n\nrecords-acknowledged\nThe total number of records a MongoDB source task passed to the Kafka Connect framework that were then successfully written to Kafka.",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_connect_mongodb_source_task_metrics_records{job=\"kafka-connect\", env=\"$env\",instance=~\"$instance\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",connector=~\"$connector\",task=~\"source-task-0\"}",
     "legendFormat": "total - {{connector}}-{{task}}"
    },
    {
     "expr": "kafka_connect_mongodb_source_task_metrics_records_acknowledged{job=\"kafka-connect\", env=\"$env\",instance=~\"$instance\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",connector=~\"$connector\",task=~\"source-task-0\"}",
     "legendFormat": "acknowledged - {{connector}}-{{task}}"
    },
    {
     "expr": "kafka_connect_mongodb_source_task_metrics_records_filtered{job=\"kafka-connect\", env=\"$env\",instance=~\"$instance\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",connector=~\"$connector\",task=~\"source-task-0\"}",
     "legendFormat": "filtered - {{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Bytes Read",
   "type": "stat",
   "description": "\t\nThe total number of bytes a MongoDB source task read from the MongoDB cluster.",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_connect_mongodb_source_task_metrics_mongodb_bytes_read{job=\"kafka-connect\", env=\"$env\",instance=~\"$instance\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",connector=~\"$connector\",task=~\"source-task-0\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Average Size of Documents",
   "type": "stat",
   "description": "Perform the following calculation with the mongodb-bytes-read and records metrics",
   "gridPos": { "h": 6, "w": 4, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_connect_mongodb_source_task_metrics_mongodb_bytes_read{job=\"kafka-connect\", env=\"$env\",instance=~\"$instance\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",connector=~\"$connector\",task=~\"source-task-0\"} / kafka_connect_mongodb_source_task_metrics_records{job=\"kafka-connect\", env=\"$env\",instance=~\"$instance\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",connector=~\"$connector\",task=~\"source-task-0\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Latest Mongodb Time Difference",
   "type": "stat",
   "description": "latest-mongodb-time-difference-secs\n\n\t\nThe number of seconds of the most recent time difference recorded between a MongoDB cluster and the post-batch resume token held by a MongoDB source task. This value is calculated by subtracting the timestamp of the task's post-batch resume token from the operationTime value of the most recent successful MongoDB command executed by the task.",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_connect_mongodb_source_task_metrics_latest_mongodb_time_difference_secs{job=\"kafka-connect\", env=\"$env\",instance=~\"$instance\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",connector=~\"$connector\",task=~\"source-task-0\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "in Task poll duration",
   "type": "timeseries",
   "description": "The total number of milliseconds the Kafka Connect framework spent executing the poll() method of a MongoDB source task.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(kafka_connect_mongodb_source_task_metrics_in_task_poll_duration_ms{job=\"kafka-connect\", env=\"$env\",instance=~\"$instance\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",connector=~\"$connector\",task=~\"source-task-0\"}[5m])",
     "legendFormat": "total - {{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "in Task poll duration by range",
   "type": "timeseries",
   "description": "The total number of milliseconds the Kafka Connect framework spent executing the poll() method of a MongoDB source task.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(kafka_connect_mongodb_source_task_metrics_in_task_poll_duration_over_1_ms{job=\"kafka-connect\", env=\"$env\",instance=~\"$instance\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",connector=~\"$connector\",task=~\"source-task-0\"}[5m])",
     "legendFormat": "> 1ms - {{connector}}-{{task}}"
    },
    {
     "expr": "rate(kafka_connect_mongodb_source_task_metrics_in_task_poll_duration_over_10_ms{job=\"kafka-connect\", env=\"$env\",instance=~\"$instance\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",connector=~\"$connector\",task=~\"source-task-0\"}[5m])",
     "legendFormat": "> 10ms - {{connector}}-{{task}}"
    },
    {
     "expr": "rate(kafka_connect_mongodb_source_task_metrics_in_task_poll_duration_over_100_ms{job=\"kafka-connect\", env=\"$env\",instance=~\"$instance\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",connector=~\"$connector\",task=~\"source-task-0\"}[5m])",
     "legendFormat": "> 100ms - {{connector}}-{{task}}"
    },
    {
     "expr": "rate(kafka_connect_mongodb_source_task_metrics_in_task_poll_duration_over_1000_ms{job=\"kafka-connect\", env=\"$env\",instance=~\"$instance\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",connector=~\"$connector\",task=~\"source-task-0\"}[5m])",
     "legendFormat": "> 1000ms - {{connector}}-{{task}}"
    },
    {
     "expr": "rate(kafka_connect_mongodb_source_task_metrics_in_task_poll_duration_over_10000_ms{job=\"kafka-connect\", env=\"$env\",instance=~\"$instance\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",connector=~\"$connector\",task=~\"source-task-0\"}[5m])",
     "legendFormat": "> 10000ms - {{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "in Connect Framework poll duration",
   "type": "timeseries",
   "description": "The total number of milliseconds spent executing code in the Kafka Connect framework since the framework first invoked the poll() method of the MongoDB source task. This metric does not count time executing code in the MongoDB sink task towards the total.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(kafka_connect_mongodb_source_task_metrics_in_connect_framework_duration_ms{job=\"kafka-connect\", env=\"$env\",instance=~\"$instance\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",connector=~\"$connector\",task=~\"source-task-0\"}[5m])",
     "legendFormat": "total - {{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "in Connect Framework poll duration by range",
   "type": "timeseries",
   "description": "The total number of milliseconds spent executing code in the Kafka Connect framework since the framework first invoked the poll() method of the MongoDB source task. This metric does not count time executing code in the MongoDB sink task towards the total.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(kafka_connect_mongodb_source_task_metrics_in_connect_framework_duration_over_1_ms{job=\"kafka-connect\", env=\"$env\",instance=~\"$instance\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",connector=~\"$connector\",task=~\"source-task-0\"}[5m])",
     "legendFormat": "> 1ms - {{connector}}-{{task}}"
    },
    {
     "expr": "rate(kafka_connect_mongodb_source_task_metrics_in_connect_framework_duration_over_10_ms{job=\"kafka-connect\", env=\"$env\",instance=~\"$instance\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",connector=~\"$connector\",task=~\"source-task-0\"}[5m])",
     "legendFormat": "> 10ms - {{connector}}-{{task}}"
    },
    {
     "expr": "rate(kafka_connect_mongodb_source_task_metrics_in_connect_framework_duration_over_100_ms{job=\"kafka-connect\", env=\"$env\",instance=~\"$instance\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",connector=~\"$connector\",task=~\"source-task-0\"}[5m])",
     "legendFormat": "> 100ms - {{connector}}-{{task}}"
    },
    {
     "expr": "rate(kafka_connect_mongodb_source_task_metrics_in_connect_framework_duration_over_1000_ms{job=\"kafka-connect\", env=\"$env\",instance=~\"$instance\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",connector=~\"$connector\",task=~\"source-task-0\"}[5m])",
     "legendFormat": "> 1000ms - {{connector}}-{{task}}"
    },
    {
     "expr": "rate(kafka_connect_mongodb_source_task_metrics_in_connect_framework_duration_over_10000_ms{job=\"kafka-connect\", env=\"$env\",instance=~\"$instance\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",connector=~\"$connector\",task=~\"source-task-0\"}[5m])",
     "legendFormat": "> 10000ms - {{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{job=\"kafka-connect\",env=\"$env\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",instance=~\"$instance\"}[5m])",
       "legendFormat": "{{kafka_connect_cluster_id}}-{{instance}}"
      }
     ]
    },
    {
     "title": "JVM Memory Used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum without(area)(jvm_memory_bytes_used{job=\"kafka-connect\",env=\"$env\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",instance=~\"$instance\"})",
       "legendFormat": "{{kafka_connect_cluster_id}}-{{instance}}"
      },
      {
       "expr": "jvm_memory_bytes_max{job=\"kafka-connect\",env=\"$env\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",instance=~\"$instance\",area=\"heap\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "JVM GC time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"kafka-connect\",env=\"$env\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",instance=~\"$instance\"}[5m]))",
       "legendFormat": "{{kafka_connect_cluster_id}}-{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}