{
 "title": "Oracle XStream CDC Monitoring",
 "description": "Monitoring Dashboard for Oracle XStream CDC Connector",
 "tags": [
  "oracle",
  "xstream",
  "confluent"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "name",
    "label": "Connector Name",
    "query": "label_values(debezium_metrics_Connected, name)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(debezium_metrics_Connected, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Oracle XStream Streaming Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Connected to Oracle",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_Connected{context=\"streaming\",instance=\"$instance\",name=\"$name\"}"
    }
   ]
  },
  {
   "title": "Committed Transactions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "debezium_metrics_NumberOfCommittedTransactions{context=\"streaming\",instance=\"$instance\",name=\"$name\"}"
    }
   ]
  },
  {
   "title": "Streaming Lag From Source",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "debezium_metrics_MilliSecondsBehindSource{context=\"streaming\",instance=\"$instance\",name=\"$name\"}",
     "legendFormat": "Streaming Lag From Source"
    }
   ]
  },
  {
   "title": "Change Event Queue Remaining Capacity (Streaming)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "debezium_metrics_QueueRemainingCapacity{context=\"streaming\",instance=\"$instance\",name=\"$name\"}",
     "legendFormat": "Streaming"
    }
   ]
  },
  {
   "title": "Total Number Of Streaming Events Seen",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "debezium_metrics_TotalNumberOfEventsSeen{context=\"streaming\",instance=\"$instance\",name=\"$name\"}",
     "legendFormat": "Total Streaming Events Seen"
    }
   ]
  },
  {
   "title": "Commit LCR behind Source in MilliSeconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "debezium_metrics_CommitMilliSecondsBehindSource{context=\"streaming\",instance=\"$instance\",name=\"$name\"}",
     "legendFormat": "Commit LCR behind Source"
    }
   ]
  },
  {
   "title": "Oracle XStream Snapshot Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }
  },
  {
   "title": "Total Table Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "debezium_metrics_TotalTableCount{context=\"snapshot\",instance=\"$instance\",name=\"$name\"}"
    }
   ]
  },
  {
   "title": "Remaining Tables",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 14 },
   "targets": [
    {
     "expr": "debezium_metrics_RemainingTableCount{context=\"snapshot\",instance=\"$instance\",name=\"$name\"}"
    }
   ]
  },
  {
   "title": "Snapshot Running",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "debezium_metrics_SnapshotRunning{context=\"snapshot\",instance=\"$instance\",name=\"$name\"}"
    }
   ]
  },
  {
   "title": "Change Event Queue Remaining Capacity (Snapshot)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "debezium_metrics_QueueRemainingCapacity{context=\"snapshot\",instance=\"$instance\",name=\"$name\"}",
     "legendFormat": "Snapshot"
    }
   ]
  },
  {
   "title": "Total Number Of Snapshot Events Seen",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "debezium_metrics_TotalNumberOfEventsSeen{context=\"snapshot\",instance=\"$instance\",name=\"$name\"}",
     "legendFormat": "Total Snapshot Events Seen"
    }
   ]
  },
  { "title": "Oracle Schema History Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Schema Changes Applied",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "debezium_metrics_ChangesApplied{context=\"schema-history\",instance=\"$instance\",name=\"$name\"}"
    }
   ]
  },
  {
   "title": "DDL Parse Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "debezium_metrics_TotalSchemaChangeParseErrorCount{context=\"streaming\",instance=\"$instance\",name=\"$name\"}"
    }
   ]
  }
 ]
}