---
services:
  connect:
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-azure-service-bus

  simple-send:
    image: eclipse-temurin:11-jre
    hostname: simple-send
    container_name: simple-send
    volumes:
      - ../../connect/connect-azure-service-bus-source/QueuesGettingStarted/target/queuesgettingstarted-1.0.0-jar-with-dependencies.jar:/queuesgettingstarted-1.0.0-jar-with-dependencies.jar:ro
    command: ["sleep", "infinity"]
    depends_on:
      - broker