#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
source ${DIR}/../../scripts/utils.sh

log "🔌 Confluent Cloud Fully Managed Connectors"
log "==========================================="
log ""
log "Run any connector with:"
log "  playground run -f ccloud/terraform-cloud-connector/playground-auto-{connector}.sh"
log ""
log "Or use the universal script:"
log "  playground run -f ccloud/terraform-cloud-connector/playground-auto-connector.sh -- --connector TYPE"
log ""
log "Available Connectors:"
log ""
log "AWS Connectors:"
log "  playground-auto-s3-sink.sh          - Stream to S3"
log "  playground-auto-s3-source.sh        - Read from S3"
log "  playground-auto-kinesis-source.sh   - Kinesis source"
log "  playground-auto-kinesis-sink.sh     - Kinesis sink"
log "  playground-auto-lambda-sink.sh      - Lambda sink"
log "  playground-auto-dynamodb-sink.sh    - DynamoDB sink"
log ""
log "GCP Connectors:"
log "  playground-auto-gcs-sink.sh         - Cloud Storage sink"
log "  playground-auto-bigquery-sink.sh    - BigQuery sink"
log "  playground-auto-pubsub-source.sh    - Pub/Sub source"
log ""
log "Azure Connectors:"
log "  playground-auto-azure-blob-sink.sh  - Blob Storage sink"
log "  playground-auto-azure-eventhubs-source.sh - Event Hubs source"
log ""
log "Database Connectors:"
log "  playground-auto-postgres-source.sh  - PostgreSQL CDC source"
log "  playground-auto-postgres-sink.sh    - PostgreSQL sink"
log "  playground-auto-mysql-source.sh     - MySQL CDC source"
log "  playground-auto-mongodb-sink.sh     - MongoDB sink"
log ""
log "NoSQL Connectors:"
log "  playground-auto-elasticsearch-sink.sh - Elasticsearch sink"
log "  playground-auto-redis-sink.sh       - Redis sink"
log ""
log "Other Connectors:"
log "  playground-auto-http-sink.sh        - HTTP sink"
log "  playground-auto-snowflake-sink.sh   - Snowflake sink"
log "  playground-auto-salesforce-source.sh - Salesforce CDC source"
log ""
log "📚 Documentation:"
log "  See PLAYGROUND_RUN_GUIDE.md for details"
