#!/bin/sh

echo 'Configuring Oracle for user myuser'

# Set archive log mode and enable GG replication
ORACLE_SID=ORCLCDB
export ORACLE_SID

sqlplus /nolog <<- EOF
	CONNECT sys/Admin123 AS SYSDBA
        -- Turn on Archivelog Mode
	SHUTDOWN IMMEDIATE
	STARTUP MOUNT
	ALTER DATABASE ARCHIVELOG;
	ALTER DATABASE FLASHBACK ON;
	ALTER DATABASE OPEN;
        -- Should show "Database log mode: Archive Mode"
	ARCHIVE LOG LIST
	exit;
EOF

# Create C##MYUSER user in CDB (see https://github.com/oracle/docker-images/issues/443#issuecomment-313157302)
sqlplus / as sysdba <<- EOF
	CREATE ROLE C##CDC_PRIVS;
	GRANT CREATE SESSION TO C##CDC_PRIVS;
	GRANT EXECUTE ON SYS.DBMS_LOGMNR TO C##CDC_PRIVS;
	GRANT LOGMINING TO C##CDC_PRIVS;
	GRANT SELECT ON V_\$LOGMNR_CONTENTS TO C##CDC_PRIVS;
	GRANT SELECT ON V_\$DATABASE TO C##CDC_PRIVS;
	GRANT SELECT ON V_\$THREAD TO C##CDC_PRIVS;
	GRANT SELECT ON V_\$PARAMETER TO C##CDC_PRIVS;
	GRANT SELECT ON V_\$NLS_PARAMETERS TO C##CDC_PRIVS;
	GRANT SELECT ON V_\$TIMEZONE_NAMES TO C##CDC_PRIVS;
	GRANT SELECT ON ALL_INDEXES TO C##CDC_PRIVS;
	GRANT SELECT ON ALL_OBJECTS TO C##CDC_PRIVS;
	GRANT SELECT ON ALL_USERS TO C##CDC_PRIVS;
	GRANT SELECT ON ALL_CATALOG TO C##CDC_PRIVS;
	GRANT SELECT ON ALL_CONSTRAINTS TO C##CDC_PRIVS;
	GRANT SELECT ON ALL_CONS_COLUMNS TO C##CDC_PRIVS;
	GRANT SELECT ON ALL_TAB_COLS TO C##CDC_PRIVS;
	GRANT SELECT ON ALL_IND_COLUMNS TO C##CDC_PRIVS;
	GRANT SELECT ON ALL_ENCRYPTED_COLUMNS TO C##CDC_PRIVS;
	GRANT SELECT ON ALL_LOG_GROUPS TO C##CDC_PRIVS;
	GRANT SELECT ON ALL_TAB_PARTITIONS TO C##CDC_PRIVS;
	GRANT SELECT ON SYS.DBA_REGISTRY TO C##CDC_PRIVS;
	GRANT SELECT ON SYS.OBJ\$ TO C##CDC_PRIVS;
	GRANT SELECT ON DBA_TABLESPACES TO C##CDC_PRIVS;
	GRANT SELECT ON DBA_OBJECTS TO C##CDC_PRIVS;
	GRANT SELECT ON SYS.ENC\$ TO C##CDC_PRIVS;
	GRANT SELECT ANY TABLE TO C##CDC_PRIVS;
	
	CREATE USER C##MYUSER IDENTIFIED BY mypassword DEFAULT TABLESPACE USERS;
	ALTER USER C##MYUSER QUOTA UNLIMITED ON USERS;

	GRANT C##CDC_PRIVS to C##MYUSER;

	GRANT CREATE TABLE TO C##MYUSER container=all;
	GRANT CREATE SEQUENCE TO C##MYUSER container=all;
	GRANT CREATE TRIGGER TO C##MYUSER container=all;
	GRANT FLASHBACK ANY TABLE TO C##MYUSER container=all;

        -- Enable Supplemental Logging for All Columns
	ALTER SESSION SET CONTAINER=cdb\$root;
	ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;
	ALTER DATABASE ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

	GRANT EXECUTE ON SYS.DBMS_LOGMNR TO C##CDC_PRIVS;
	GRANT EXECUTE ON SYS.DBMS_LOGMNR_D TO C##CDC_PRIVS;
	GRANT EXECUTE ON SYS.DBMS_LOGMNR_LOGREP_DICT TO C##CDC_PRIVS;
	GRANT EXECUTE ON SYS.DBMS_LOGMNR_SESSION TO C##CDC_PRIVS;

	-- only required to execute DBMS_LOCK.SLEEP (not required by connector)
	GRANT EXECUTE ON DBMS_LOCK TO C##CDC_PRIVS;

	exit;
EOF

