#########################
# README
# if you modify this file, you will need to rebuild manually the 'connect' service:
#
# $ cd environment/<env name>
# $ docker-compose build connect
#
#########################

FROM confluentinc/cp-kafka-connect-base:5.3.1

RUN     confluent-hub install --no-prompt confluentinc/kafka-connect-http:latest \
		&& confluent-hub install --no-prompt confluentinc/kafka-connect-jdbc:latest \
		&& confluent-hub install --no-prompt confluentinc/kafka-connect-elasticsearch:latest \
