FROM confluentinc/cp-kafka-connect-base:5.3.1

RUN     confluent-hub install --no-prompt confluentinc/kafka-connect-http:latest \
		&& confluent-hub install --no-prompt confluentinc/kafka-connect-jdbc:latest \
