{
 "title": "Confluent Cloud Cost",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Environment",
    "query": {
     "query": "label_values(confluent_cloud_cost_amount, environment)"
    }
   },
   {
    "name": "Kafka",
    "query": {
     "query": "label_values(confluent_cloud_cost_amount{id=~\"lkc.*\",environment=~\"$Environment\"}, id)"
    }
   },
   {
    "name": "Connectors",
    "query": {
     "query": "label_values(confluent_cloud_cost_amount{id=~\"lcc.*\",environment=~\"$Environment\"}, id)"
    }
   },
   {
    "name": "KSQL",
    "query": {
     "query": "label_values(confluent_cloud_cost_amount{id=~\"lksqlc.*\",environment=~\"$Environment\"}, id)"
    }
   },
   {
    "name": "Flink",
    "query": {
     "query": "label_values(confluent_cloud_cost_amount{id=~\"lfcp.*\",environment=~\"$Environment\"}, id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Confluent Cloud Costs",
   "type": "canvas",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(confluent_cloud_cost_amount)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(confluent_cloud_cost_amount{id=~\"lkc.*\",environment=~\"$Environment\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(confluent_cloud_cost_amount{id=~\"lcc.*\",environment=~\"$Environment\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(confluent_cloud_cost_amount{id=~\"lfcp.*\",environment=~\"$Environment\",id=~\"$Flink\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(confluent_cloud_cost_amount{id=~\"lksqlc.*\",environment=~\"$Environment\",id=~\"$KSQL\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(confluent_cloud_cost_amount{id=~\"lsrc.*\", environment=~\"$Environment\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Breakdown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "By Day",
   "type": "bargauge",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(end_date)(confluent_cloud_cost_amount{environment=~\"$Environment\"})",
     "legendFormat": "{{end_date}}"
    }
   ]
  },
  {
   "title": "by Product",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 7, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(product)(confluent_cloud_cost_amount{environment=~\"$Environment\"})",
     "legendFormat": "{{ product }}"
    }
   ]
  },
  {
   "title": "by Line Type",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 8, "x": 7, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(line_type)(confluent_cloud_cost_amount{environment=~\"$Environment\"})",
     "legendFormat": "{{ product }}"
    }
   ]
  },
  {
   "title": "by Network Access Type",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 9, "x": 15, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(network_access_type)(confluent_cloud_cost_amount{environment=~\"$Environment\"})",
     "legendFormat": "{{ network_access_type }}"
    }
   ]
  },
  {
   "title": "by Environment",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(environment)(confluent_cloud_cost_amount{environment=~\"$Environment\"})",
     "legendFormat": "{{ environment }}"
    }
   ]
  },
  { "title": "Confluent Kafka ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Confluent Kafka Clusters",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(confluent_cloud_cost_amount{id=~\"lkc.*\",environment=~\"$Environment\"})"
    }
   ]
  },
  {
   "title": "Kafka Clusters",
   "type": "bargauge",
   "gridPos": { "h": 18, "w": 17, "x": 7, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(id,resource)(confluent_cloud_cost_amount{id=~\"lkc.*\",environment=~\"$Environment\",id=~\"$Kafka\"})",
     "legendFormat": "{{ id }} - {{ resource }}"
    }
   ]
  },
  {
   "title": "Line Type",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(confluent_cloud_cost_amount{id=~\"lkc.*\",environment=~\"$Environment\",id=~\"$Kafka\"}) by (line_type)",
     "legendFormat": "{{line_type}}"
    }
   ]
  },
  {
   "title": "Confluent Connectors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "collapsed": true,
   "panels": [
    {
     "title": "Confluent Connectors",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(confluent_cloud_cost_amount{id=~\"lcc.*\",environment=~\"$Environment\"})"
      }
     ]
    },
    {
     "title": "Line Type",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 6, "x": 4, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(confluent_cloud_cost_amount{id=~\"lcc.*\",environment=~\"$Environment\",id=~\"$Connectors\"}) by (line_type)",
       "legendFormat": "{{line_type}}"
      }
     ]
    },
    {
     "title": "Connectors",
     "type": "bargauge",
     "gridPos": { "h": 23, "w": 24, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (id,resource)(confluent_cloud_cost_amount{id=~\"lcc.*\",environment=~\"$Environment\",id=~\"$Connectors\"})",
       "legendFormat": "{{ id }} - {{ resource }}"
      }
     ]
    }
   ]
  },
  {
   "title": "KSQL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "collapsed": true,
   "panels": [
    {
     "title": "KSQLDB",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(confluent_cloud_cost_amount{id=~\"lksqlc.*\",environment=~\"$Environment\",id=~\"$KSQL\"})",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "Line Type",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(confluent_cloud_cost_amount{id=~\"lksqlc.*\",environment=~\"$Environment\", id=~\"$KSQL\"}) by (line_type)",
       "legendFormat": "{{line_type}}"
      }
     ]
    },
    {
     "title": "KSQL",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 23, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (id,resource)(confluent_cloud_cost_amount{id=~\"lksqlc.*\",environment=~\"$Environment\", id=~\"$KSQL\"})",
       "legendFormat": "{{ id }} - {{ resource }}"
      }
     ]
    }
   ]
  },
  { "title": "Flink", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Flink",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(confluent_cloud_cost_amount{id=~\"lfcp.*\",environment=~\"$Environment\",id=~\"$Flink\"})",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Line Type",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(confluent_cloud_cost_amount{id=~\"lfcp.*\",environment=~\"$Environment\",id=~\"$Flink\"}) by (line_type)",
     "legendFormat": "{{line_type}}"
    }
   ]
  },
  {
   "title": "Flink",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (id,resource)(confluent_cloud_cost_amount{id=~\"lfcp.*\",environment=~\"$Environment\", id=~\"$Flink\"})",
     "legendFormat": "{{ id }} - {{ resource }}"
    }
   ]
  },
  {
   "title": "All",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cost by Resource",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (id) (confluent_cloud_cost_amount)",
       "legendFormat": "{{ id }}"
      }
     ]
    }
   ]
  }
 ]
}