#!/bin/sh

echo 'Creating CUSTOMERS table in PDB'

ORACLE_SID=ORCLCDB
export ORACLE_SID

# sqlplus / as sysdba <<- EOF
# GRANT CREATE TABLESPACE TO C##MYUSER container=all;
# GRANT UNLIMITED TABLESPACE TO C##MYUSER container=all;
# EOF

sqlplus C\#\#MYUSER/mypassword@//localhost:1521/ORCLPDB1  <<- EOF

  create table CUSTOMERS (
          RECID VARCHAR2(255 BYTE),
          XMLRECORD XMLTYPE
  ) XMLTYPE XMLRECORD STORE AS BINARY XML;

  ALTER TABLE "CUSTOMERS" ADD CONSTRAINT "PK_CUSTOMERS" PRIMARY KEY ("RECID");
  ALTER TABLE "CUSTOMERS" MODIFY ("RECID" NOT NULL ENABLE);

EOF


# workaround
# sqlplus C\#\#MYUSER/mypassword@//localhost:1521/ORCLPDB1  <<- EOF

#   create table CUSTOMERS (
#           RECID VARCHAR2(255 BYTE),
#           XMLRECORD XMLTYPE,
#           UPDATED_AT timestamp DEFAULT CURRENT_TIMESTAMP
#   ) XMLTYPE XMLRECORD STORE AS BINARY XML;

#   ALTER TABLE "CUSTOMERS" ADD CONSTRAINT "PK_CUSTOMERS" PRIMARY KEY ("RECID");
#   ALTER TABLE "CUSTOMERS" MODIFY ("RECID" NOT NULL ENABLE);

#   CREATE OR REPLACE TRIGGER TRG_CUSTOMERS_UPD
#   BEFORE INSERT OR UPDATE ON CUSTOMERS
#   REFERENCING NEW AS NEW_ROW
#     FOR EACH ROW
#   BEGIN
#     SELECT SYSDATE
#           INTO :NEW_ROW.UPDATED_AT
#           FROM DUAL;
#   END;
#   /

# EOF