#!/bin/sh

echo 'Creating CUSTOMERS table in PDB'

ORACLE_SID=ORCLCDB
export ORACLE_SID

sqlplus / as sysdba <<- EOF
GRANT CREATE TABLESPACE TO C##MYUSER container=all;
GRANT UNLIMITED TABLESPACE TO C##MYUSER container=all;
EOF

sqlplus C\#\#MYUSER/mypassword@//localhost:1521/ORCLPDB1  <<- EOF
  CREATE TABLESPACE MY_DATA 
   DATAFILE 'data.dbf' 
   SIZE 1m;

  create table CUSTOMERS (
          RECID VARCHAR2(255 BYTE),
          XMLRECORD XMLTYPE
  ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MY_DATA"   NO INMEMORY 
  XMLTYPE COLUMN "XMLRECORD" STORE AS SECUREFILE BINARY XML (
  TABLESPACE "MY_DATA" ENABLE STORAGE IN ROW CHUNK 8192
  CACHE  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ALLOW NONSCHEMA DISALLOW ANYSCHEMA ;

  ALTER TABLE "CUSTOMERS" ADD CONSTRAINT "PK_CUSTOMERS" PRIMARY KEY ("RECID");
  ALTER TABLE "CUSTOMERS" MODIFY ("RECID" NOT NULL ENABLE);

EOF

