---
services:

  dksybase:
    image: ifnazar/sybase_15_7:latest
    hostname: dksybase
    container_name: dksybase
    command: ["bash", "/sybase/start"]
    ports:
      - "5000:5000"

  connect:
    depends_on:
      - dksybase
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-jdbc