---
services:

  cassandra:
    image: cassandra:4.1
    hostname: cassandra
    container_name: cassandra
    ports:
      - "9042:9042"
    # enable username/password authentication (default superuser is cassandra/cassandra)
    command:
      - "bash"
      - "-c"
      - "sed -i 's/^authenticator:.*/authenticator: PasswordAuthenticator/' /etc/cassandra/cassandra.yaml && exec docker-entrypoint.sh cassandra -f"

  # https://ngrok.com/docs/using-ngrok-with/docker/
  ngrok:
    image: ngrok/ngrok:latest
    hostname: ngrok
    container_name: ngrok
    ports:
      - 4040:4040
    restart: unless-stopped
    depends_on:
      - cassandra
    command:
      - "start"
      - "--all"
      - "--log=stdout"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ../../ccloud/fm-datastax-sink/ngrok.yml:/etc/ngrok.yml
    environment:
      NGROK_AUTHTOKEN: $NGROK_AUTH_TOKEN
