---
services:

  squid:
    image: ubuntu/squid
    hostname: squid
    container_name: squid
    ports:
      - "8888:8888"
    volumes:
      - ../../connect/connect-salesforce-pushtopics-source/squid/passwords:/etc/squid/passwords
      - ../../connect/connect-salesforce-pushtopics-source/squid/squid.conf:/etc/squid/squid.conf

  sfdx-cli:
    # forked from salestrip/sfdx-cli to add plugin sfpowerkit
    image: vdesabou/sfdx-cli:latest
    hostname: sfdx-cli
    container_name: sfdx-cli
    entrypoint: ["sh", "-c", "sleep infinity"]
    volumes:
    - ../../connect/connect-salesforce-pushtopics-source/MyLeadPushTopics.apex:/tmp/MyLeadPushTopics.apex

  connect:
    volumes:
      - ../../connect/connect-salesforce-pushtopics-source/salesforce-confluent.keystore.jks:/tmp/salesforce-confluent.keystore.jks
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-salesforce
    #dns: 0.0.0.0