#!/bin/bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
source ${DIR}/../../scripts/utils.sh

if connect_cp_version_greater_than_8 && [ ! -z "$CONNECTOR_TAG" ] && ! version_gt $CONNECTOR_TAG "10.7.99"
then
     logwarn "minimal supported connector version is 10.8.0 for CP 8.0"
     logwarn "see https://docs.confluent.io/platform/current/connect/supported-connector-version-8.1.html#supported-connector-versions-in-cp-8-1"
     exit 111
fi

cd ../../connect/connect-jdbc-sap-hana-source
if [ ! -f ${PWD}/ngdbc-2.12.9.jar ]
then
     log "Downloading ngdbc-2.12.9.jar "
     wget -q https://repo1.maven.org/maven2/com/sap/cloud/db/jdbc/ngdbc/2.12.9/ngdbc-2.12.9.jar
fi
cd -

PLAYGROUND_ENVIRONMENT=${PLAYGROUND_ENVIRONMENT:-"plaintext"}
playground start-environment --environment "${PLAYGROUND_ENVIRONMENT}" --docker-compose-override-file "${PWD}/docker-compose.plaintext.yml"


playground container logs --container sap --wait-for-log "Startup finished!" --max-wait 600
log "SAP HANA has started!"

log "Create table in SAP HANA"
docker exec -i sap /usr/sap/HXE/HDB90/exe/hdbsql -i 90 -d HXE -u LOCALDEV -p Localdev1  > /tmp/result.log  2>&1 <<-EOF
CREATE COLUMN TABLE CUSTOMERS(ID BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,FIRST_NAME VARCHAR(30),LAST_NAME VARCHAR(30));
INSERT INTO CUSTOMERS(FIRST_NAME,LAST_NAME) VALUES ('John','Doe');
EOF
cat /tmp/result.log

log "Creating SAP HANA JDBC Source connector"
playground connector create-or-update --connector jdbc-sap-hana-source  << EOF
{
               "tasks.max": "1",
               "connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector",
               "mode": "incrementing",
               "table.whitelist": "CUSTOMERS",
               "incrementing.column.name": "ID",
               "connection.url": "jdbc:sap://sap:39041/?databaseName=HXE&reconnect=true&statementCacheSize=512",
               "connection.user": "LOCALDEV",
               "connection.password" : "Localdev1",
               "topic.prefix": "sap-hana-"
          }
EOF

sleep 5

log "Verifying topic sap-hana-CUSTOMERS"
playground topic consume --topic sap-hana-CUSTOMERS --min-expected-messages 1 --timeout 60

