# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/user_created_event.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/user_created_event.proto',
  package='protos',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x1fprotos/user_created_event.proto\x12\x06protos\x1a\x1fgoogle/protobuf/timestamp.proto\"~\n\x10UserCreatedEvent\x12\x10\n\x08\x65vent_id\x18\x01 \x02(\t\x12\x33\n\x0f\x65vent_timestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x12\n\nevent_name\x18\x03 \x02(\t\x12\x0f\n\x07version\x18\x04 \x02(\t'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_USERCREATEDEVENT = _descriptor.Descriptor(
  name='UserCreatedEvent',
  full_name='protos.UserCreatedEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='event_id', full_name='protos.UserCreatedEvent.event_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='event_timestamp', full_name='protos.UserCreatedEvent.event_timestamp', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='event_name', full_name='protos.UserCreatedEvent.event_name', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='protos.UserCreatedEvent.version', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=202,
)

_USERCREATEDEVENT.fields_by_name['event_timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['UserCreatedEvent'] = _USERCREATEDEVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserCreatedEvent = _reflection.GeneratedProtocolMessageType('UserCreatedEvent', (_message.Message,), {
  'DESCRIPTOR' : _USERCREATEDEVENT,
  '__module__' : 'protos.user_created_event_pb2'
  # @@protoc_insertion_point(class_scope:protos.UserCreatedEvent)
  })
_sym_db.RegisterMessage(UserCreatedEvent)


# @@protoc_insertion_point(module_scope)
