---
services:

  postgres:
    build:
      context: ../../connect/connect-debezium-postgresql-source/ssl
    hostname: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
     - ../../connect/connect-debezium-postgresql-source/ssl/my-postgres.conf:/tmp/postgresql.conf
     - ../../connect/connect-debezium-postgresql-source/ssl/pg_hba.conf:/tmp/pg_hba.conf
    command:
      - postgres
      - -c
      - config_file=/tmp/postgresql.conf
      - -c
      - hba_file=/tmp/pg_hba.conf

  connect:
    depends_on:
      - postgres
    volumes:
      - ../../connect/connect-debezium-postgresql-source/ssl/ca.crt:/tmp/ca.crt
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/debezium-debezium-connector-postgresql
      # KAFKA_OPTS: -Djavax.net.debug=all