// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: optionaltest.proto

package com.github.vdesabou;

public final class OptionalTestImpl {
  private OptionalTestImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OptionalTestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.github.vdesabou.OptionalTest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *doc entry
     * </pre>
     *
     * <code>int32 field_no_optional = 1;</code>
     * @return The fieldNoOptional.
     */
    int getFieldNoOptional();

    /**
     * <pre>
     *doc entry
     * </pre>
     *
     * <code>string field_first_optional = 2;</code>
     * @return Whether the fieldFirstOptional field is set.
     */
    boolean hasFieldFirstOptional();
    /**
     * <pre>
     *doc entry
     * </pre>
     *
     * <code>string field_first_optional = 2;</code>
     * @return The fieldFirstOptional.
     */
    java.lang.String getFieldFirstOptional();
    /**
     * <pre>
     *doc entry
     * </pre>
     *
     * <code>string field_first_optional = 2;</code>
     * @return The bytes for fieldFirstOptional.
     */
    com.google.protobuf.ByteString
        getFieldFirstOptionalBytes();

    /**
     * <pre>
     *doc entry
     * </pre>
     *
     * <code>int32 field_second_optional = 3;</code>
     * @return Whether the fieldSecondOptional field is set.
     */
    boolean hasFieldSecondOptional();
    /**
     * <pre>
     *doc entry
     * </pre>
     *
     * <code>int32 field_second_optional = 3;</code>
     * @return The fieldSecondOptional.
     */
    int getFieldSecondOptional();

    /**
     * <pre>
     *doc entry
     * </pre>
     *
     * <code>string field_third_optional = 4;</code>
     * @return Whether the fieldThirdOptional field is set.
     */
    boolean hasFieldThirdOptional();
    /**
     * <pre>
     *doc entry
     * </pre>
     *
     * <code>string field_third_optional = 4;</code>
     * @return The fieldThirdOptional.
     */
    java.lang.String getFieldThirdOptional();
    /**
     * <pre>
     *doc entry
     * </pre>
     *
     * <code>string field_third_optional = 4;</code>
     * @return The bytes for fieldThirdOptional.
     */
    com.google.protobuf.ByteString
        getFieldThirdOptionalBytes();
  }
  /**
   * Protobuf type {@code com.github.vdesabou.OptionalTest}
   */
  public static final class OptionalTest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.github.vdesabou.OptionalTest)
      OptionalTestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use OptionalTest.newBuilder() to construct.
    private OptionalTest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OptionalTest() {
      fieldFirstOptional_ = "";
      fieldThirdOptional_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new OptionalTest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private OptionalTest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              fieldNoOptional_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              fieldFirstOptional_ = s;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000002;
              fieldSecondOptional_ = input.readInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              fieldThirdOptional_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.vdesabou.OptionalTestImpl.internal_static_com_github_vdesabou_OptionalTest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.vdesabou.OptionalTestImpl.internal_static_com_github_vdesabou_OptionalTest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.vdesabou.OptionalTestImpl.OptionalTest.class, com.github.vdesabou.OptionalTestImpl.OptionalTest.Builder.class);
    }

    private int bitField0_;
    public static final int FIELD_NO_OPTIONAL_FIELD_NUMBER = 1;
    private int fieldNoOptional_;
    /**
     * <pre>
     *doc entry
     * </pre>
     *
     * <code>int32 field_no_optional = 1;</code>
     * @return The fieldNoOptional.
     */
    @java.lang.Override
    public int getFieldNoOptional() {
      return fieldNoOptional_;
    }

    public static final int FIELD_FIRST_OPTIONAL_FIELD_NUMBER = 2;
    private volatile java.lang.Object fieldFirstOptional_;
    /**
     * <pre>
     *doc entry
     * </pre>
     *
     * <code>string field_first_optional = 2;</code>
     * @return Whether the fieldFirstOptional field is set.
     */
    @java.lang.Override
    public boolean hasFieldFirstOptional() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     *doc entry
     * </pre>
     *
     * <code>string field_first_optional = 2;</code>
     * @return The fieldFirstOptional.
     */
    @java.lang.Override
    public java.lang.String getFieldFirstOptional() {
      java.lang.Object ref = fieldFirstOptional_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fieldFirstOptional_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *doc entry
     * </pre>
     *
     * <code>string field_first_optional = 2;</code>
     * @return The bytes for fieldFirstOptional.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFieldFirstOptionalBytes() {
      java.lang.Object ref = fieldFirstOptional_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fieldFirstOptional_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FIELD_SECOND_OPTIONAL_FIELD_NUMBER = 3;
    private int fieldSecondOptional_;
    /**
     * <pre>
     *doc entry
     * </pre>
     *
     * <code>int32 field_second_optional = 3;</code>
     * @return Whether the fieldSecondOptional field is set.
     */
    @java.lang.Override
    public boolean hasFieldSecondOptional() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     *doc entry
     * </pre>
     *
     * <code>int32 field_second_optional = 3;</code>
     * @return The fieldSecondOptional.
     */
    @java.lang.Override
    public int getFieldSecondOptional() {
      return fieldSecondOptional_;
    }

    public static final int FIELD_THIRD_OPTIONAL_FIELD_NUMBER = 4;
    private volatile java.lang.Object fieldThirdOptional_;
    /**
     * <pre>
     *doc entry
     * </pre>
     *
     * <code>string field_third_optional = 4;</code>
     * @return Whether the fieldThirdOptional field is set.
     */
    @java.lang.Override
    public boolean hasFieldThirdOptional() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     *doc entry
     * </pre>
     *
     * <code>string field_third_optional = 4;</code>
     * @return The fieldThirdOptional.
     */
    @java.lang.Override
    public java.lang.String getFieldThirdOptional() {
      java.lang.Object ref = fieldThirdOptional_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fieldThirdOptional_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *doc entry
     * </pre>
     *
     * <code>string field_third_optional = 4;</code>
     * @return The bytes for fieldThirdOptional.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFieldThirdOptionalBytes() {
      java.lang.Object ref = fieldThirdOptional_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fieldThirdOptional_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (fieldNoOptional_ != 0) {
        output.writeInt32(1, fieldNoOptional_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, fieldFirstOptional_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(3, fieldSecondOptional_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, fieldThirdOptional_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (fieldNoOptional_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, fieldNoOptional_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, fieldFirstOptional_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, fieldSecondOptional_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, fieldThirdOptional_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.vdesabou.OptionalTestImpl.OptionalTest)) {
        return super.equals(obj);
      }
      com.github.vdesabou.OptionalTestImpl.OptionalTest other = (com.github.vdesabou.OptionalTestImpl.OptionalTest) obj;

      if (getFieldNoOptional()
          != other.getFieldNoOptional()) return false;
      if (hasFieldFirstOptional() != other.hasFieldFirstOptional()) return false;
      if (hasFieldFirstOptional()) {
        if (!getFieldFirstOptional()
            .equals(other.getFieldFirstOptional())) return false;
      }
      if (hasFieldSecondOptional() != other.hasFieldSecondOptional()) return false;
      if (hasFieldSecondOptional()) {
        if (getFieldSecondOptional()
            != other.getFieldSecondOptional()) return false;
      }
      if (hasFieldThirdOptional() != other.hasFieldThirdOptional()) return false;
      if (hasFieldThirdOptional()) {
        if (!getFieldThirdOptional()
            .equals(other.getFieldThirdOptional())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FIELD_NO_OPTIONAL_FIELD_NUMBER;
      hash = (53 * hash) + getFieldNoOptional();
      if (hasFieldFirstOptional()) {
        hash = (37 * hash) + FIELD_FIRST_OPTIONAL_FIELD_NUMBER;
        hash = (53 * hash) + getFieldFirstOptional().hashCode();
      }
      if (hasFieldSecondOptional()) {
        hash = (37 * hash) + FIELD_SECOND_OPTIONAL_FIELD_NUMBER;
        hash = (53 * hash) + getFieldSecondOptional();
      }
      if (hasFieldThirdOptional()) {
        hash = (37 * hash) + FIELD_THIRD_OPTIONAL_FIELD_NUMBER;
        hash = (53 * hash) + getFieldThirdOptional().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.vdesabou.OptionalTestImpl.OptionalTest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.vdesabou.OptionalTestImpl.OptionalTest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.vdesabou.OptionalTestImpl.OptionalTest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.vdesabou.OptionalTestImpl.OptionalTest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.vdesabou.OptionalTestImpl.OptionalTest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.vdesabou.OptionalTestImpl.OptionalTest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.vdesabou.OptionalTestImpl.OptionalTest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.vdesabou.OptionalTestImpl.OptionalTest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.vdesabou.OptionalTestImpl.OptionalTest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.vdesabou.OptionalTestImpl.OptionalTest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.vdesabou.OptionalTestImpl.OptionalTest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.vdesabou.OptionalTestImpl.OptionalTest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.vdesabou.OptionalTestImpl.OptionalTest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.github.vdesabou.OptionalTest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.github.vdesabou.OptionalTest)
        com.github.vdesabou.OptionalTestImpl.OptionalTestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.vdesabou.OptionalTestImpl.internal_static_com_github_vdesabou_OptionalTest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.vdesabou.OptionalTestImpl.internal_static_com_github_vdesabou_OptionalTest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.vdesabou.OptionalTestImpl.OptionalTest.class, com.github.vdesabou.OptionalTestImpl.OptionalTest.Builder.class);
      }

      // Construct using com.github.vdesabou.OptionalTestImpl.OptionalTest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        fieldNoOptional_ = 0;

        fieldFirstOptional_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        fieldSecondOptional_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        fieldThirdOptional_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.vdesabou.OptionalTestImpl.internal_static_com_github_vdesabou_OptionalTest_descriptor;
      }

      @java.lang.Override
      public com.github.vdesabou.OptionalTestImpl.OptionalTest getDefaultInstanceForType() {
        return com.github.vdesabou.OptionalTestImpl.OptionalTest.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.vdesabou.OptionalTestImpl.OptionalTest build() {
        com.github.vdesabou.OptionalTestImpl.OptionalTest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.vdesabou.OptionalTestImpl.OptionalTest buildPartial() {
        com.github.vdesabou.OptionalTestImpl.OptionalTest result = new com.github.vdesabou.OptionalTestImpl.OptionalTest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.fieldNoOptional_ = fieldNoOptional_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.fieldFirstOptional_ = fieldFirstOptional_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.fieldSecondOptional_ = fieldSecondOptional_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.fieldThirdOptional_ = fieldThirdOptional_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.vdesabou.OptionalTestImpl.OptionalTest) {
          return mergeFrom((com.github.vdesabou.OptionalTestImpl.OptionalTest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.vdesabou.OptionalTestImpl.OptionalTest other) {
        if (other == com.github.vdesabou.OptionalTestImpl.OptionalTest.getDefaultInstance()) return this;
        if (other.getFieldNoOptional() != 0) {
          setFieldNoOptional(other.getFieldNoOptional());
        }
        if (other.hasFieldFirstOptional()) {
          bitField0_ |= 0x00000001;
          fieldFirstOptional_ = other.fieldFirstOptional_;
          onChanged();
        }
        if (other.hasFieldSecondOptional()) {
          setFieldSecondOptional(other.getFieldSecondOptional());
        }
        if (other.hasFieldThirdOptional()) {
          bitField0_ |= 0x00000004;
          fieldThirdOptional_ = other.fieldThirdOptional_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.vdesabou.OptionalTestImpl.OptionalTest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.vdesabou.OptionalTestImpl.OptionalTest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int fieldNoOptional_ ;
      /**
       * <pre>
       *doc entry
       * </pre>
       *
       * <code>int32 field_no_optional = 1;</code>
       * @return The fieldNoOptional.
       */
      @java.lang.Override
      public int getFieldNoOptional() {
        return fieldNoOptional_;
      }
      /**
       * <pre>
       *doc entry
       * </pre>
       *
       * <code>int32 field_no_optional = 1;</code>
       * @param value The fieldNoOptional to set.
       * @return This builder for chaining.
       */
      public Builder setFieldNoOptional(int value) {
        
        fieldNoOptional_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *doc entry
       * </pre>
       *
       * <code>int32 field_no_optional = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFieldNoOptional() {
        
        fieldNoOptional_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object fieldFirstOptional_ = "";
      /**
       * <pre>
       *doc entry
       * </pre>
       *
       * <code>string field_first_optional = 2;</code>
       * @return Whether the fieldFirstOptional field is set.
       */
      public boolean hasFieldFirstOptional() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       *doc entry
       * </pre>
       *
       * <code>string field_first_optional = 2;</code>
       * @return The fieldFirstOptional.
       */
      public java.lang.String getFieldFirstOptional() {
        java.lang.Object ref = fieldFirstOptional_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fieldFirstOptional_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *doc entry
       * </pre>
       *
       * <code>string field_first_optional = 2;</code>
       * @return The bytes for fieldFirstOptional.
       */
      public com.google.protobuf.ByteString
          getFieldFirstOptionalBytes() {
        java.lang.Object ref = fieldFirstOptional_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fieldFirstOptional_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *doc entry
       * </pre>
       *
       * <code>string field_first_optional = 2;</code>
       * @param value The fieldFirstOptional to set.
       * @return This builder for chaining.
       */
      public Builder setFieldFirstOptional(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        fieldFirstOptional_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *doc entry
       * </pre>
       *
       * <code>string field_first_optional = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFieldFirstOptional() {
        bitField0_ = (bitField0_ & ~0x00000001);
        fieldFirstOptional_ = getDefaultInstance().getFieldFirstOptional();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *doc entry
       * </pre>
       *
       * <code>string field_first_optional = 2;</code>
       * @param value The bytes for fieldFirstOptional to set.
       * @return This builder for chaining.
       */
      public Builder setFieldFirstOptionalBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000001;
        fieldFirstOptional_ = value;
        onChanged();
        return this;
      }

      private int fieldSecondOptional_ ;
      /**
       * <pre>
       *doc entry
       * </pre>
       *
       * <code>int32 field_second_optional = 3;</code>
       * @return Whether the fieldSecondOptional field is set.
       */
      @java.lang.Override
      public boolean hasFieldSecondOptional() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       *doc entry
       * </pre>
       *
       * <code>int32 field_second_optional = 3;</code>
       * @return The fieldSecondOptional.
       */
      @java.lang.Override
      public int getFieldSecondOptional() {
        return fieldSecondOptional_;
      }
      /**
       * <pre>
       *doc entry
       * </pre>
       *
       * <code>int32 field_second_optional = 3;</code>
       * @param value The fieldSecondOptional to set.
       * @return This builder for chaining.
       */
      public Builder setFieldSecondOptional(int value) {
        bitField0_ |= 0x00000002;
        fieldSecondOptional_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *doc entry
       * </pre>
       *
       * <code>int32 field_second_optional = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearFieldSecondOptional() {
        bitField0_ = (bitField0_ & ~0x00000002);
        fieldSecondOptional_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object fieldThirdOptional_ = "";
      /**
       * <pre>
       *doc entry
       * </pre>
       *
       * <code>string field_third_optional = 4;</code>
       * @return Whether the fieldThirdOptional field is set.
       */
      public boolean hasFieldThirdOptional() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       *doc entry
       * </pre>
       *
       * <code>string field_third_optional = 4;</code>
       * @return The fieldThirdOptional.
       */
      public java.lang.String getFieldThirdOptional() {
        java.lang.Object ref = fieldThirdOptional_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fieldThirdOptional_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *doc entry
       * </pre>
       *
       * <code>string field_third_optional = 4;</code>
       * @return The bytes for fieldThirdOptional.
       */
      public com.google.protobuf.ByteString
          getFieldThirdOptionalBytes() {
        java.lang.Object ref = fieldThirdOptional_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fieldThirdOptional_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *doc entry
       * </pre>
       *
       * <code>string field_third_optional = 4;</code>
       * @param value The fieldThirdOptional to set.
       * @return This builder for chaining.
       */
      public Builder setFieldThirdOptional(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        fieldThirdOptional_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *doc entry
       * </pre>
       *
       * <code>string field_third_optional = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearFieldThirdOptional() {
        bitField0_ = (bitField0_ & ~0x00000004);
        fieldThirdOptional_ = getDefaultInstance().getFieldThirdOptional();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *doc entry
       * </pre>
       *
       * <code>string field_third_optional = 4;</code>
       * @param value The bytes for fieldThirdOptional to set.
       * @return This builder for chaining.
       */
      public Builder setFieldThirdOptionalBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000004;
        fieldThirdOptional_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.github.vdesabou.OptionalTest)
    }

    // @@protoc_insertion_point(class_scope:com.github.vdesabou.OptionalTest)
    private static final com.github.vdesabou.OptionalTestImpl.OptionalTest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.vdesabou.OptionalTestImpl.OptionalTest();
    }

    public static com.github.vdesabou.OptionalTestImpl.OptionalTest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OptionalTest>
        PARSER = new com.google.protobuf.AbstractParser<OptionalTest>() {
      @java.lang.Override
      public OptionalTest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OptionalTest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OptionalTest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OptionalTest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.vdesabou.OptionalTestImpl.OptionalTest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_vdesabou_OptionalTest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_vdesabou_OptionalTest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022optionaltest.proto\022\023com.github.vdesabo" +
      "u\"\337\001\n\014OptionalTest\022\031\n\021field_no_optional\030" +
      "\001 \001(\005\022!\n\024field_first_optional\030\002 \001(\tH\000\210\001\001" +
      "\022\"\n\025field_second_optional\030\003 \001(\005H\001\210\001\001\022!\n\024" +
      "field_third_optional\030\004 \001(\tH\002\210\001\001B\027\n\025_fiel" +
      "d_first_optionalB\030\n\026_field_second_option" +
      "alB\027\n\025_field_third_optionalB\022B\020OptionalT" +
      "estImplb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_github_vdesabou_OptionalTest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_github_vdesabou_OptionalTest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_vdesabou_OptionalTest_descriptor,
        new java.lang.String[] { "FieldNoOptional", "FieldFirstOptional", "FieldSecondOptional", "FieldThirdOptional", "FieldFirstOptional", "FieldSecondOptional", "FieldThirdOptional", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
