---
services:
  hbase:
    # https://github.com/pomadchin/hbase-docker
    image: daunnc/hbase:2.2.4
    hostname: hbase
    container_name: hbase

  connect:
    depends_on:
      - hbase
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-hbase