---
services:

  elasticsearch:
    image: elasticsearch:8.18.2
    hostname: elasticsearch
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    command:
      - elasticsearch
      - -Ediscovery.type=single-node
      - -Enetwork.host=0.0.0.0
      - -Expack.security.enabled=false
      - -Expack.security.http.ssl.enabled=false
      - -Expack.security.transport.ssl.enabled=false
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      
  connect:
    depends_on:
      - elasticsearch
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-elasticsearch