name: Update Docs

on:
  workflow_dispatch:

jobs:
  update-docs:
    name: Update Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          repository: vdesabou/kafka-docker-playground
          fetch-depth: 0
          ssh-strict: 'false'

      - name: Update DOCS
        run: |
          sudo gem install bashly
          cd ./scripts/cli
          ./playground update-docs

      - name: Pushes docs
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.CI_GITHUB_TOKEN }}
        with:
          source_file: './docs'
          destination_repo: 'vdesabou/kafka-docker-playground-docs'
          user_email: 'vincent.desaboulin@gmail.com'
          user_name: 'vdesabou'
          commit_message: 'updating with latest versions'
