
sqlplus myuser/mypassword@//localhost:1521/XE  <<- EOF

DROP TABLE MYTABLE PURGE;

CREATE TABLE MYTABLE (
  ID           NUMBER(10)    NOT NULL,
  DESCRIPTION  VARCHAR2(50)  NOT NULL,
  UPDATE_TS TIMESTAMP);

ALTER TABLE MYTABLE ADD (
  CONSTRAINT MYTABLE_PK PRIMARY KEY (ID));

CREATE SEQUENCE MYTABLE_SEQ START WITH 1;

CREATE OR REPLACE TRIGGER MYTABLE_TRIGGER_ID
BEFORE INSERT ON MYTABLE
FOR EACH ROW

BEGIN
  SELECT MYTABLE_SEQ.NEXTVAL
  INTO   :new.id
  FROM   dual;
END;
/

CREATE OR REPLACE TRIGGER MYTABLE_TRIGGER_TS
BEFORE INSERT OR UPDATE ON MYTABLE
REFERENCING NEW AS NEW_ROW
  FOR EACH ROW
BEGIN
  SELECT SYSDATE
        INTO :NEW_ROW.UPDATE_TS
        FROM DUAL;
END;
/

INSERT INTO MYTABLE (
  id,
  description
) VALUES (
  1,
  'kafka'
);

commit;

EOF

